import json
from pathlib import Path
p=Path('outreach_queue.jsonl')
new=[
{"id":"gpass-us-309","date":"2026-03-02","source":"Google-First","client":"DeGeorge Plumbing & HVAC","contact_name":"","phone":"(602) 641-3172","email":"","location":"Phoenix, AZ","service":"Plumbing/HVAC","estimated_value":1080,"status":"new","notes":"Search snippet highlights direct booking CTA for plumbing/HVAC service with published local line.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16026413172","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":84,"priority_tier":"P1","website_quality":"strong_local_site"},
{"id":"gpass-us-310","date":"2026-03-02","source":"Google-First","client":"Arid Valley Plumbing","contact_name":"","phone":"(602) 999-4741","email":"","location":"Phoenix, AZ","service":"Plumbing","estimated_value":980,"status":"new","notes":"Snippet repeats call-now number and same intake line for residential plumbing requests.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16029994741","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":79,"priority_tier":"P2","website_quality":"strong_local_site"},
{"id":"gpass-us-311","date":"2026-03-02","source":"Google-First","client":"Smiley Plumbing","contact_name":"","phone":"(602) 910-6582","email":"","location":"Phoenix, AZ","service":"Plumbing","estimated_value":960,"status":"new","notes":"Homepage snippet positions residential plumbing + drain cleaning with visible direct phone.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16029106582","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":77,"priority_tier":"P2","website_quality":"strong_local_site"},
{"id":"gpass-us-312","date":"2026-03-02","source":"Google-First","client":"Suburban Heating & Air Conditioning","contact_name":"","phone":"(214) 381-1127","email":"","location":"Dallas, TX","service":"HVAC","estimated_value":1010,"status":"new","notes":"Dallas HVAC listing snippet includes direct service line and contact-form CTA for immediate dispatch.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+12143811127","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":82,"priority_tier":"P1","website_quality":"strong_local_site"},
{"id":"gpass-us-313","date":"2026-03-02","source":"Google-First","client":"EHS HVAC","contact_name":"","phone":"(214) 612-7493","email":"","location":"Dallas, TX","service":"HVAC","estimated_value":990,"status":"new","notes":"Service-area snippet lists 24/7 HVAC availability and a published Dallas office phone.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+12146127493","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":80,"priority_tier":"P2","website_quality":"strong_local_site"},
{"id":"gpass-us-314","date":"2026-03-02","source":"Google-First","client":"InPhaze Electric","contact_name":"","phone":"(407) 599-7777","email":"","location":"Orlando, FL","service":"Electrical","estimated_value":970,"status":"new","notes":"Residential electrician snippet emphasizes 30+ years and includes direct Orlando call line.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+14075997777","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":78,"priority_tier":"P2","website_quality":"strong_local_site"},
{"id":"gpass-us-315","date":"2026-03-02","source":"Google-First","client":"Frank Gay Services","contact_name":"","phone":"(407) 512-8102","email":"ask@frankgayservices.com","location":"Orlando, FL","service":"Electrical/HVAC/Plumbing","estimated_value":1120,"status":"new","notes":"Accessibility/contact snippet publishes both support phone and ask@frankgayservices.com inbox.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+14075128102","phone_validation":"verified_via_google_snippet","email_validation":"verified_via_google_snippet","channel_flags":{"can_call":True,"can_dm":False,"can_email":True,"can_sms":True},"outreach_usable":True,"verification_status":"verified_email_phone","primary_channel":"email_then_call","priority_score":86,"priority_tier":"P1","website_quality":"strong_local_site"},
{"id":"gpass-us-316","date":"2026-03-02","source":"Google-First","client":"Mister Sparky Orlando","contact_name":"","phone":"(407) 477-2159","email":"","location":"Orlando, FL","service":"Electrical","estimated_value":985,"status":"new","notes":"Orlando office snippet includes full local address plus direct phone for service scheduling.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+14074772159","phone_validation":"verified_via_google_snippet","email_validation":"missing","channel_flags":{"can_call":True,"can_dm":False,"can_email":False,"can_sms":True},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":79,"priority_tier":"P2","website_quality":"strong_local_site"}
]
with p.open('a',encoding='utf-8') as f:
    for o in new:
        f.write(json.dumps(o)+"\n")
print('\n'.join([o['id'] for o in new]))
