import json, pathlib
p=pathlib.Path('outreach_queue.jsonl')
entries=[
{"id":"nosite-103","date":"2026-03-02","source":"Yelp","client":"Valle Landscaping","contact_name":"","phone":"(480) 806-9550","email":"","location":"Phoenix, AZ","service":"Landscaping","estimated_value":900,"status":"new","notes":"Yelp-only profile (no website); established 2022 with direct phone listed.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+14808069550","phone_validation":"verified_via_yelp_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":86,"priority_tier":"P1"},
{"id":"nosite-104","date":"2026-03-02","source":"Yelp","client":"Jose's Landscaping","contact_name":"","phone":"(623) 396-8694","email":"","location":"Phoenix, AZ","service":"Landscaping","estimated_value":880,"status":"new","notes":"No-website Yelp listing; high activity profile (110 photos) with verified phone.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16233968694","phone_validation":"verified_via_yelp_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":85,"priority_tier":"P1"},
{"id":"nosite-105","date":"2026-03-02","source":"Yelp","client":"Divine Design Landscaping Phoenix","contact_name":"","phone":"(602) 769-4564","email":"","location":"Phoenix, AZ","service":"Landscaping","estimated_value":920,"status":"new","notes":"Yelp listing without standalone site; strong intent signal from large review volume and phone CTA.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16027694564","phone_validation":"verified_via_yelp_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":89,"priority_tier":"P1"},
{"id":"nosite-106","date":"2026-03-02","source":"Yelp","client":"MasterAZScapes","contact_name":"","phone":"(602) 975-3648","email":"","location":"Phoenix, AZ","service":"Landscaping","estimated_value":900,"status":"new","notes":"Established landscaping operator (since 2019) with Yelp phone listed and no owned website.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+16029753648","phone_validation":"verified_via_yelp_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":87,"priority_tier":"P1"},
{"id":"nosite-107","date":"2026-03-02","source":"Craigslist","client":"License DFW Pest Control","contact_name":"","phone":"(214) 430-4504","email":"","location":"Dallas, TX","service":"Pest Control","estimated_value":840,"status":"new","notes":"Licensed family-run pest control ad with direct phone and no website funnel.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+12144304504","phone_validation":"verified_via_craigslist_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":82,"priority_tier":"P2"},
{"id":"nosite-108","date":"2026-03-02","source":"Craigslist","client":"American Residential HVAC","contact_name":"","phone":"(702) 600-3291","email":"","location":"Las Vegas, NV","service":"HVAC","estimated_value":930,"status":"new","notes":"Established HVAC operator (2009) with licensing mention and direct-call contact only.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+17026003291","phone_validation":"verified_via_craigslist_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":88,"priority_tier":"P1"},
{"id":"nosite-109","date":"2026-03-02","source":"Craigslist","client":"Dunn-Rite Roofing Houston","contact_name":"","phone":"(877) 537-3317","email":"","location":"Houston, TX","service":"Roofing","estimated_value":980,"status":"new","notes":"Roofing offer-led listing with direct hotline and no website destination; high-ticket category.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+18775373317","phone_validation":"verified_via_craigslist_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":84,"priority_tier":"P2"},
{"id":"nosite-110","date":"2026-03-02","source":"Craigslist","client":"Affordable Fence Repair Portland","contact_name":"","phone":"(971) 708-3671","email":"","location":"Portland, OR","service":"Fencing","estimated_value":860,"status":"new","notes":"Fence repair specialist with CCB license noted; direct phone intake and no website capture.","owner_name":"","owner_name_validation":"missing","phone_normalized":"+19717083671","phone_validation":"verified_via_craigslist_listing","email_validation":"missing","channel_flags":{"can_call":True,"can_sms":True,"can_email":False,"can_dm":False},"outreach_usable":True,"verification_status":"verified_phone_only","primary_channel":"sms_or_call","priority_score":83,"priority_tier":"P2"}
]
with p.open('a',encoding='utf-8') as f:
    for e in entries:
        f.write('\n'+json.dumps(e,separators=(',',':')))
print('\n'.join(e['id'] for e in entries))
