import os
base=r"C:\Users\chead\.openclaw\workspace-john\sites\premium-v3-wave95"
os.makedirs(base, exist_ok=True)
leads=[
 {'id':'gpass-pnw-248','name':'Spokane Roofing Company','location':'Spokane / Liberty Lake, WA','service':'Roofing','est':1250,'slug':'spokane-roofing-company-spokane-liberty-lake-wa','tags':['High Intent','Storm Repair','Fast Quote Funnel']},
 {'id':'gpass-pnw-208','name':'Lobo Roofing LLC','location':'Tacoma, WA 98404','service':'Roofing','est':1200,'slug':'lobo-roofing-llc-tacoma-wa-98404','tags':['High Intent','Residential Roofing','Phone Lead Capture']},
 {'id':'gpass-pnw-210','name':'Elite Metal Roofing LLC','location':'SW Washington Metro (Vancouver area), WA','service':'Roofing','est':1200,'slug':'elite-metal-roofing-llc-sw-washington-metro-vancouver-area-wa','tags':['High Intent','Metal Roofing','Premium Project Leads']},
 {'id':'gpass-pnw-219','name':'A Better Roofing Company','location':'Seattle, WA','service':'Residential Roofing','est':1200,'slug':'a-better-roofing-company-seattle-wa','tags':['High Intent','Roof Replacement','Urgent Estimate CTA']},
 {'id':'gpass-pnw-220','name':'Quality Pacific Roofing','location':'Seattle, WA 98122','service':'Residential Roofing','est':1200,'slug':'quality-pacific-roofing-seattle-wa-98122','tags':['High Intent','Leak Repair','Conversion-First Intake']},
]
style=':root{--bg:#0a0f1f;--panel:#121a33;--text:#eaf0ff;--muted:#b8c4e4;--line:#2a3f73;--a:#5cc8ff;--b:#76ffbf}*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:radial-gradient(circle at top,#13244a,#0a0f1f 60%);color:var(--text)}.wrap{max-width:1100px;margin:auto;padding:28px 18px}.grid{display:grid;gap:14px}.hero{grid-template-columns:1.25fr .95fr}.two{grid-template-columns:1fr 1fr}.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}h1,h2{line-height:1.2}.meta{color:var(--muted);font-size:13px}.btn{display:inline-block;padding:12px 16px;border-radius:10px;font-weight:700;text-decoration:none}.pri{background:linear-gradient(90deg,var(--a),var(--b));color:#021023;border:none;cursor:pointer}.tag{display:inline-block;padding:6px 10px;border:1px solid #365089;background:#1a2850;border-radius:999px;margin:0 8px 8px 0;color:var(--muted);font-size:12px}form{display:grid;gap:9px}label{font-size:13px;color:var(--muted)}input,textarea{width:100%;padding:11px;border-radius:8px;border:1px solid #39528f;background:#0e1730;color:var(--text)}textarea{min-height:100px}li{margin:8px 0}@media(max-width:860px){.hero,.two{grid-template-columns:1fr}}'
for l in leads:
 d=os.path.join(base,l['slug']); os.makedirs(d,exist_ok=True)
 tags=''.join([f'<span class="tag">{t}</span>' for t in l['tags']])
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>{l['name']} | {l['service']} Quote Demo</title><style>{style}</style></head><body><div class="wrap"><div class="grid hero"><section class="card"><p class="meta">Lead ID: {l['id']} | {l['location']} | {l['service']}</p><h1>{l['name']}</h1><p>Premium conversion demo tailored for {l['service'].lower()} buyers in {l['location']}.</p><p>Built to capture high-intent local traffic and turn quote requests into booked estimate calls.</p><p><a class="btn pri" href="#quote">Get My Quote</a></p><div>{tags}</div></section><section class="card"><h2 style="margin-top:0">Request a Quick Callback</h2><form action="/contact" method="post"><input type="hidden" name="business" value="{l['slug']}"/><input type="hidden" name="source" value="quick_callback"/><label for="name">Full Name</label><input id="name" name="name" type="text" autocomplete="name" aria-label="Full Name" required/><label for="phone">Phone Number</label><input id="phone" name="phone" type="tel" autocomplete="tel" aria-label="Phone Number" required/><button class="btn pri" type="submit">Request Callback</button></form></section></div><div class="grid two" style="margin-top:12px"><section class="card"><h2 style="margin-top:0">Conversion Architecture</h2><ul><li>Urgency-aligned hero copy for high-intent {l['service'].lower()} searches in {l['location']}.</li><li>Dual conversion paths: quick callback form plus detailed quote request.</li><li>Trust-focused positioning for local homeowners and property managers.</li><li>All form submissions route to <code>/contact</code> with source attribution fields.</li></ul></section><section class="card" id="quote"><h2 style="margin-top:0">Detailed Quote Request</h2><form action="/contact" method="post"><input type="hidden" name="business" value="{l['slug']}"/><input type="hidden" name="source" value="detailed_quote"/><label for="qname">Full Name</label><input id="qname" name="name" type="text" autocomplete="name" aria-label="Full Name" required/><label for="qphone">Phone Number</label><input id="qphone" name="phone" type="tel" autocomplete="tel" aria-label="Phone Number" required/><label for="details">Project details</label><textarea id="details" name="details" aria-label="Project details" required></textarea><button class="btn pri" type="submit">Send My Quote Request</button></form><p class="meta">Priority response via quote form. Demo form posts to secure contact intake endpoint.</p></section></div></div></body></html>'''
 with open(os.path.join(d,'index.html'),'w',encoding='utf-8') as f: f.write(html)
notes=['# Premium V3 Wave 95 Deployment Notes','','Generated: 2026-03-03','','## Scope','Built 5 premium demo pages for highest-intent uncovered leads under `sites/premium-v3-wave95/`.','Each page includes:','- Hero CTA linking to `#quote`','- Quick callback form posting to `/contact`','- Detailed quote form posting to `/contact`','- Hidden tracking fields (`business`, `source`) for intake attribution','','## Lead selection method','Selected highest estimated-value uncovered roofing leads from `outreach_queue.jsonl` by checking slug coverage against existing `sites/premium-v3-wave*/` folders, then prioritizing high-intent/P1-ready records.','','## Pages']
for i,l in enumerate(leads,1):
 notes.append(f"{i}. `{l['slug']}` (Lead: {l['id']} | {l['name']} | {l['location']} | {l['service']} | est ${l['est']})")
notes += ['', '## Deployment checks','- Verify each `index.html` renders correctly on mobile and desktop.','- Confirm both forms on each page POST to `/contact`.','- Confirm hidden `business` values exactly match folder slugs.','- Smoke test hero CTA jump to `#quote` on all pages.']
with open(os.path.join(base,'DEPLOYMENT_NOTES.md'),'w',encoding='utf-8') as f: f.write('\n'.join(notes))
print('created',len(leads),'pages in',base)
