import json

entries = [
{"id":"sprint12-20260304-001","date":"2026-03-04","source":"Upwork","client":"Upwork Excel Freelance Jobs Board","service":"Excel automation + data cleanup","estimated_value":600,"status":"new","url":"https://www.upwork.com/freelance-jobs/excel/","notes":"1,886 open Excel jobs indicates immediate demand pool. Outreach angle: respond to fresh posts offering 24-hour cleanup + automation starter package."},
{"id":"sprint12-20260304-002","date":"2026-03-04","source":"Upwork","client":"Upwork Microsoft Excel Jobs Board","service":"Spreadsheet process automation","estimated_value":700,"status":"new","url":"https://www.upwork.com/freelance-jobs/microsoft-excel/","notes":"1,586 open jobs. Angle: target clients with repetitive reporting pain; offer fixed-scope workbook optimization + SOP handoff."},
{"id":"sprint12-20260304-003","date":"2026-03-04","source":"Upwork","client":"Upwork Excel VBA Jobs Board","service":"VBA macro automation","estimated_value":1200,"status":"new","url":"https://www.upwork.com/freelance-jobs/excel-vba/","notes":"Snippet mentions consolidation analyst need. Angle: sell 'replace manual consolidation with one-click macro pipeline'."},
{"id":"sprint12-20260304-004","date":"2026-03-04","source":"Upwork","client":"Upwork Spreadsheets Jobs Board","service":"Sheets-to-dashboard automation","estimated_value":650,"status":"new","url":"https://www.upwork.com/freelance-jobs/spreadsheets/","notes":"3,568 openings suggests large TAM. Angle: position as rapid turnaround partner for backlog spreadsheet fixes."},
{"id":"sprint12-20260304-005","date":"2026-03-04","source":"Upwork","client":"Upwork VLOOKUP Tables Jobs Board","service":"Formula repair + model hardening","estimated_value":500,"status":"new","url":"https://www.upwork.com/freelance-jobs/vlookup-tables/","notes":"Snippet: experienced Excel specialist needed to improve existing workbook. Angle: audit + formula refactor in 48h."},
{"id":"sprint12-20260304-006","date":"2026-03-04","source":"Upwork","client":"Upwork Excel PowerPivot Jobs Board","service":"PowerPivot reporting automation","estimated_value":900,"status":"new","url":"https://www.upwork.com/freelance-jobs/microsoft-excel-powerpivot/","notes":"153 focused jobs; high-intent analytics buyers. Angle: package PowerPivot model + executive dashboard."},

{"id":"sprint12-20260304-007","date":"2026-03-04","source":"Fiverr","client":"alizee0","service":"White-label data entry + sheet operations","estimated_value":300,"status":"new","url":"https://www.fiverr.com/alizee0/do-fast-and-accurate-data-entry-for-excel-or-google-sheets","notes":"Seller already pitching fast data entry. Partnership angle: offer backend overflow capacity + automation upgrades for higher-ticket upsells."},
{"id":"sprint12-20260304-008","date":"2026-03-04","source":"Fiverr","client":"anila109","service":"Data cleaning partnership","estimated_value":250,"status":"new","url":"https://www.fiverr.com/anila109/excel-data-cleaning-formatting","notes":"Low-ticket cleaner likely has volume. Angle: help convert one-off cleanup buyers into recurring monthly spreadsheet maintenance."},
{"id":"sprint12-20260304-009","date":"2026-03-04","source":"Fiverr","client":"freelance_sid","service":"CSV merge automation","estimated_value":350,"status":"new","url":"https://www.fiverr.com/freelance_sid/clean-organize-and-merge-your-excel-or-csv-data","notes":"Gig centered on manual merge/clean tasks. Angle: pitch macro templates to reduce delivery time and increase margins."},
{"id":"sprint12-20260304-010","date":"2026-03-04","source":"Fiverr","client":"dtecheditor","service":"Inventory dashboard automation","estimated_value":500,"status":"new","url":"https://www.fiverr.com/dtecheditor/create-inventory-dashboard-in-excel","notes":"Inventory dashboard niche is strong SMB fit. Angle: joint delivery on dashboard + automated import pipeline."},
{"id":"sprint12-20260304-011","date":"2026-03-04","source":"Fiverr","client":"yashikakakkar29","service":"Dashboard + data model partner","estimated_value":450,"status":"new","url":"https://www.fiverr.com/yashikakakkar29/clean-your-data-and-create-beautiful-excel-dashboard","notes":"Positions on dashboards/data modeling. Angle: offer backend model QA + faster fulfillment for review growth."},
{"id":"sprint12-20260304-012","date":"2026-03-04","source":"Fiverr","client":"hudavinci","service":"Inventory macro enhancement","estimated_value":600,"status":"new","url":"https://www.fiverr.com/hudavinci/develop-automated-inventory-tool-for-your-business","notes":"Already sells inventory VBA tool; high-probability B2B pain niche. Angle: co-build premium version (alerts, forecasting, reporting)."},

{"id":"sprint12-20260304-013","date":"2026-03-04","source":"Reddit","client":"r/forhire user (Excel scheduling post)","service":"Scheduling workbook automation","estimated_value":400,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1aizmuz/hiring_someone_who_can_make_an_excel_sheet_for/","notes":"Explicit hiring intent for scheduling spreadsheet. Angle: offer robust scheduler with validation + auto conflict checks."},
{"id":"sprint12-20260304-014","date":"2026-03-04","source":"Reddit","client":"r/forhire user (Urgent rate adjustment)","service":"Bulk pricing/rate model fix","estimated_value":250,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1mgonir/urgent_help_needed_excel_rate_adjustment_keep/","notes":"Urgent buyer signal and clear spreadsheet pain. Angle: same-day rescue + reusable pricing model template."},
{"id":"sprint12-20260304-015","date":"2026-03-04","source":"Reddit","client":"r/slavelabour user (Separate info in Excel)","service":"Data normalization automation","estimated_value":200,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1fhff21/task_separate_information_in_an_excel_file_15/","notes":"Task implies recurring parsing need. Angle: deliver script + repeatable data split workflow, not just one-time fix."},
{"id":"sprint12-20260304-016","date":"2026-03-04","source":"Reddit","client":"r/slavelabour user (Map from Excel)","service":"Excel-to-map automation","estimated_value":350,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1di6xdo/task_export_excel_company_location_on_interactive/","notes":"Geo-visualization use case. Angle: automate geocoding and dashboard map for ongoing territory management."},
{"id":"sprint12-20260304-017","date":"2026-03-04","source":"Reddit","client":"r/slavelabour user (Filter CSV/Excel)","service":"CSV filter pipeline","estimated_value":300,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/tffu9l/task_need_someone_to_filter_excelcsv_file_will/","notes":"Budget already signaled ($50 historically) with likely repeat data loads. Angle: convert to monthly processing retainer."},
{"id":"sprint12-20260304-018","date":"2026-03-04","source":"Reddit","client":"r/slavelabour user (PDF to Excel 2500 rows)","service":"PDF ingestion + cleanup","estimated_value":350,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1gpz4kq/task_convert_pdf_to_excel/","notes":"Large row count and import errors indicate persistent ETL pain. Angle: clean converter workflow + QA checker."},
{"id":"sprint12-20260304-019","date":"2026-03-04","source":"Reddit","client":"r/forhire user (Excel to web interface)","service":"Excel-to-web workflow migration","estimated_value":900,"status":"new","url":"https://www.reddit.com/r/forhire/comments/se3pkr/hiring_translate_excelentered_recorded_time_to/","notes":"Budget range $200-$600 in original post; strategic upsell to lightweight portal + sync automation."},
{"id":"sprint12-20260304-020","date":"2026-03-04","source":"Reddit","client":"r/slavelabour user (Orders to Sheets/Excel script)","service":"Order export automation","estimated_value":700,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/11hz3og/task_scriptcode_a_program_to_export_my/","notes":"Direct automation request for ecommerce order exports. Angle: recurring connector maintenance + dashboard KPI layer."},

{"id":"sprint12-20260304-021","date":"2026-03-04","source":"LinkedIn","client":"Zoe Burkland - Burkland Bookkeeping LLC","service":"Bookkeeping spreadsheet automation","estimated_value":800,"status":"new","url":"https://www.linkedin.com/in/burklandbookkeeping/","notes":"Seattle bookkeeping owner profile. Angle: automate month-end close checklists and client reporting templates."},
{"id":"sprint12-20260304-022","date":"2026-03-04","source":"LinkedIn","client":"Oghale Agbro - AOA Bookkeeping, LLC","service":"Excel + QuickBooks reconciliation workflows","estimated_value":900,"status":"new","url":"https://www.linkedin.com/in/oghaleagbro/","notes":"Owner/operator with bookkeeping scale potential. Angle: reduce manual reconciliation and client onboarding friction."},
{"id":"sprint12-20260304-023","date":"2026-03-04","source":"LinkedIn","client":"Christy Gibson - Gibson Bookkeeping & Advisory","service":"Advisory dashboard automation","estimated_value":1000,"status":"new","url":"https://www.linkedin.com/in/christyrgibson/","notes":"Targets service-based SMBs in Seattle. Angle: white-label KPI dashboard package for her client base."},
{"id":"sprint12-20260304-024","date":"2026-03-04","source":"LinkedIn","client":"Courtney Day - Day By Day Bookkeeping, LLC","service":"Recurring reporting automation","estimated_value":800,"status":"new","url":"https://www.linkedin.com/in/courtday/","notes":"Small bookkeeping firm owner; high-fit for reusable monthly reporting automation."},
{"id":"sprint12-20260304-025","date":"2026-03-04","source":"LinkedIn","client":"Shandra Rose - Evergreen Bookkeeping Solutions","service":"Excel cleanup + workflow templates","estimated_value":750,"status":"new","url":"https://www.linkedin.com/in/shandra-rose-7b979911/","notes":"Owner profile with niche bookkeeping service. Angle: standardized workbook templates to speed client delivery."},

{"id":"sprint12-20260304-026","date":"2026-03-04","source":"Local SMB Niche","client":"The Landscape Company (Spokane Valley)","service":"Field-ops spreadsheet automation","estimated_value":1200,"status":"new","url":"https://www.linkedin.com/company/the-landscape-company","notes":"2-10 employee landscaping firm likely running manual quoting/scheduling sheets. Angle: route sheets + crew scheduling automation."},
{"id":"sprint12-20260304-027","date":"2026-03-04","source":"Local SMB Niche","client":"New Life Rockeries (Seattle)","service":"Estimate and project tracker automation","estimated_value":1100,"status":"new","url":"https://www.linkedin.com/company/b-d-rockeries","notes":"35+ years local operations implies legacy manual processes. Angle: modernize bid tracking and job-cost sheets."},
{"id":"sprint12-20260304-028","date":"2026-03-04","source":"Local SMB Niche","client":"GRO (SW Washington)","service":"Landscape operations dashboards","estimated_value":1300,"status":"new","url":"https://www.linkedin.com/company/grovancwa","notes":"Multi-service contractor profile suggests fragmented data. Angle: unify maintenance + construction reporting in one workbook stack."},
{"id":"sprint12-20260304-029","date":"2026-03-04","source":"Local SMB Niche","client":"Pacific Landscape Management (Puget Sound)","service":"Irrigation + maintenance KPI automation","estimated_value":1500,"status":"new","url":"https://www.linkedin.com/company/pacific-landscape-management_2","notes":"Regional landscape ops with recurring jobs; strong fit for recurring performance dashboards and crew productivity tracking."},
{"id":"sprint12-20260304-030","date":"2026-03-04","source":"Local SMB Niche","client":"Northwest Landscape Services (PNW)","service":"Consolidated branch reporting automation","estimated_value":1800,"status":"new","url":"https://www.linkedin.com/company/northwest-landscape-services","notes":"Larger regional org can benefit from cross-branch reporting standardization. Angle: executive scorecard from existing spreadsheets."}
]

with open('leads.jsonl', 'a', encoding='utf-8') as f:
    for entry in entries:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')

print(f"Appended {len(entries)} leads to leads.jsonl")
