import json

entries = [
{"id":"sprint-20260304-001","date":"2026-03-04","source":"Upwork","client":"Google App Scripts & Google Sheets Automation Expert Needed","service":"Google Sheets Automation","estimated_value":900,"status":"new","notes":"Upwork job post requesting App Script + Sheets workflow automation; strong fit for rapid process audit + build. Outreach angle: offer 48-hour mini-automation sprint with before/after workflow map. URL: https://www.upwork.com/freelance-jobs/apply/Google-App-Scripts-Google-Sheets-Automation-Expert-Needed_~021956158046159154118/"},
{"id":"sprint-20260304-002","date":"2026-03-04","source":"Upwork","client":"Lead Automation Specialist: Phantom Buster to Google Sheets","service":"Lead Pipeline Automation","estimated_value":1100,"status":"new","notes":"Upwork buyer needs lead extraction + Sheets sync; clear automation pain and ROI. Outreach angle: propose done-for-you pipeline with dedupe, enrichment columns, and QA checks. URL: https://www.upwork.com/freelance-jobs/apply/Lead-Automation-Specialist-Phantom-Buster-Google-Sheets_~021977768086293249315/"},
{"id":"sprint-20260304-003","date":"2026-03-04","source":"Upwork","client":"Specialist in script-based automation Google Sheets Needed ASAP","service":"Apps Script / Process Automation","estimated_value":1000,"status":"new","notes":"ASAP urgency + script-based automation request signals high close probability. Outreach angle: position as fast-turn rescue partner for brittle Sheets workflows. URL: https://www.upwork.com/freelance-jobs/apply/Specialist-script-based-automation-Google-Sheets-Needed-ASAP_~021893719905373109545/"},
{"id":"sprint-20260304-004","date":"2026-03-04","source":"Upwork","client":"Google Sheets Freelance Jobs Feed","service":"Sheet Cleanup + Automation","estimated_value":800,"status":"new","notes":"Upwork jobs feed includes form-to-sheet and report automation requests; recurring buyer pool. Outreach angle: send targeted proposals focused on reducing manual handoffs between Forms/Sheets/Slides/tools. URL: https://www.upwork.com/freelance-jobs/google-sheets/"},
{"id":"sprint-20260304-005","date":"2026-03-04","source":"Upwork","client":"Google Apps Script Freelance Jobs Feed","service":"No-code + Script Automation","estimated_value":950,"status":"new","notes":"Feed includes process mapping and company-wide automation asks; ideal for packaged automation audits. Outreach angle: offer fixed-scope process map + first automation deployment. URL: https://www.upwork.com/freelance-jobs/google-apps-script/"},
{"id":"sprint-20260304-006","date":"2026-03-04","source":"Upwork","client":"Data Analysis Freelance Jobs Feed","service":"Excel Analytics + Dashboard Automation","estimated_value":850,"status":"new","notes":"Feed snippet shows recurring Excel-heavy analyst work and data automation needs. Outreach angle: pitch dashboard + repeatable reporting template to cut weekly analyst time. URL: https://www.upwork.com/freelance-jobs/data-analysis/"},
{"id":"sprint-20260304-007","date":"2026-03-04","source":"Reddit","client":"r/forhire - Excel sheet for scheduling","service":"Custom Excel Scheduling System","estimated_value":450,"status":"new","notes":"Hiring post for scheduling workbook with multiple functions indicates direct need. Outreach angle: propose robust template + SOP video to reduce scheduling errors. URL: https://www.reddit.com/r/forhire/comments/1aizmuz/hiring_someone_who_can_make_an_excel_sheet_for/"},
{"id":"sprint-20260304-008","date":"2026-03-04","source":"Reddit","client":"r/forhire - Excel custom search/filter build","service":"Excel Tooling / Search UX","estimated_value":500,"status":"new","notes":"Requester wants advanced filtering/search behavior in Excel; high intent and clear scope. Outreach angle: deliver searchable front-end tab + clean data backend schema. URL: https://www.reddit.com/r/forhire/comments/1gofhqq/hiring_excel_expert_needed_build_custom_search/"},
{"id":"sprint-20260304-009","date":"2026-03-04","source":"Reddit","client":"r/forhire - VBA/Excel expert (more work if fast)","service":"VBA Automation","estimated_value":600,"status":"new","notes":"Post explicitly says more work available if trust/speed proven; strong repeat potential. Outreach angle: offer quick paid diagnostic and first macro turnaround same day. URL: https://www.reddit.com/r/forhire/comments/1ibg5aw/hiring_online_looking_for_vba_excel_expert_must/"},
{"id":"sprint-20260304-010","date":"2026-03-04","source":"Reddit","client":"r/forhire - Translate Excel time logs to web interface","service":"Excel-to-Web Workflow Automation","estimated_value":900,"status":"new","notes":"Budget listed ($200-$600 historically) and ongoing workflow pain between Excel and web system. Outreach angle: automate import mapping + validation to remove manual entry. URL: https://www.reddit.com/r/forhire/comments/se3pkr/hiring_translate_excelentered_recorded_time_to/"},
{"id":"sprint-20260304-011","date":"2026-03-04","source":"Reddit","client":"r/forhire - Hire Excel/Google Sheets experts regularly","service":"Retainer Spreadsheet Ops","estimated_value":1200,"status":"new","notes":"Regular-work signal makes this a high-LTV lead for recurring automation support. Outreach angle: propose monthly spreadsheet ops retainer with SLA response times. URL: https://www.reddit.com/r/forhire/comments/nem123/hiring_looking_to_hire_excelgoogle_sheets_experts/"},
{"id":"sprint-20260304-012","date":"2026-03-04","source":"Reddit","client":"r/forhire - BI/Data Analytics with Advanced Excel + Domo","service":"BI + Excel Automation","estimated_value":1400,"status":"new","notes":"BI contractor ask with Excel + Domo suggests analytics maturity and larger budgets. Outreach angle: offer phased build (data cleanup, KPI model, dashboard automation). URL: https://www.reddit.com/r/forhire/comments/91rxys/hiring_bidata_analytics_with_advanced_excel_domo/"},
{"id":"sprint-20260304-013","date":"2026-03-04","source":"Fiverr","client":"Fiverr Community: New seller struggling with Excel data cleaning gig","service":"Excel Delivery Ops / White-label Automation","estimated_value":300,"status":"new","notes":"Seller publicly asks for help getting traction; potential partner/referral source needing backend templates and faster delivery systems. Outreach angle: provide reusable cleanup/checklist automation pack they can resell. URL: https://community.fiverr.com/public/forum/boards/start-here-c9d/posts/345672-new-seller-struggling-to-get-first-order-%E2%80%94-need-help-with-my-excel-gig"},
{"id":"sprint-20260304-014","date":"2026-03-04","source":"Fiverr","client":"Fiverr Community: New seller boosting impressions (Excel/Sheets services)","service":"Proposal + Delivery Automation","estimated_value":300,"status":"new","notes":"Active seller offering spreadsheet services; likely needs process automation for quoting and fulfillment. Outreach angle: offer SOP + template bundle to increase turnaround speed. URL: https://community.fiverr.com/public/forum/boards/ask-the-community-xsm/posts/new-seller-any-tips-to-boost-impressions-and-clicks-ikwtkznfum"},
{"id":"sprint-20260304-015","date":"2026-03-04","source":"Fiverr","client":"Ranolabar Fiverr Gig - format excel worksheets","service":"White-label Excel Automation Support","estimated_value":250,"status":"new","notes":"Seller handles Excel formatting requests; strong candidate for overflow outsourcing partnership. Outreach angle: partner offer for macro-enabled upsells they currently cannot deliver quickly. URL: https://www.fiverr.com/ranolabar/format-your-excel-worksheets-to-your-request"},
{"id":"sprint-20260304-016","date":"2026-03-04","source":"Fiverr","client":"Rayjohncayabyab Fiverr Gig - Excel VBA and macro applications","service":"Subcontract/Overflow Automation","estimated_value":400,"status":"new","notes":"VBA-focused seller with request-based projects; likely has overflow or complex cases. Outreach angle: propose backend implementation support with white-label confidentiality. URL: https://www.fiverr.com/rayjohncayabyab/do-excel-vba-and-macro-applications-data-entry-and-html"},
{"id":"sprint-20260304-017","date":"2026-03-04","source":"Fiverr","client":"Anserzm Fiverr Gig - Excel templates and dashboard","service":"Dashboard Automation Collaboration","estimated_value":450,"status":"new","notes":"Dashboard seller likely receives repetitive reporting requests suitable for automation productization. Outreach angle: co-deliver dashboard + auto-refresh pipeline package. URL: https://www.fiverr.com/anserzm/excel-data-entry-for-you"},
{"id":"sprint-20260304-018","date":"2026-03-04","source":"Fiverr","client":"Snrichards Fiverr Gig - custom excel templates","service":"Spreadsheet Systemization","estimated_value":350,"status":"new","notes":"Custom template seller may benefit from reusable component library and formula automation toolkit. Outreach angle: done-with-you template framework to increase margin per order. URL: https://www.fiverr.com/snrichards/create-custom-excel-templates-spreadsheets-and-dashboards"},
{"id":"sprint-20260304-019","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Excel Freelancer Jobs (US)","service":"B2B Excel Automation Outreach","estimated_value":900,"status":"new","notes":"LinkedIn jobs page shows active Excel freelancer demand in US; recruiter and hiring-manager pool. Outreach angle: targeted DM campaign to hiring managers offering fixed-scope automation pilots. URL: https://www.linkedin.com/jobs/excel-freelancer-jobs"},
{"id":"sprint-20260304-020","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Microsoft Excel Jobs (US)","service":"Reporting Process Automation","estimated_value":1000,"status":"new","notes":"High-volume Excel jobs feed includes freelance/remote analyst listings with repetitive reporting needs. Outreach angle: offer to automate manual reporting workload before full-time hire. URL: https://www.linkedin.com/jobs/microsoft-excel-jobs"},
{"id":"sprint-20260304-021","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Post: AI tools for Excel & Google Sheets","service":"Excel/Sheets Automation Advisory","estimated_value":500,"status":"new","notes":"Engaged Excel-focused professional community around automation tooling; potential warm network for referrals. Outreach angle: share practical SMB automation use-cases and offer implementation sessions. URL: https://www.linkedin.com/posts/darrin-brown-14b44aa3_ai-powered-tools-for-excel-google-sheets-activity-7017613273311154176-v0H9"},
{"id":"sprint-20260304-022","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Work From Home Excel Jobs Feed (India)","service":"Remote Spreadsheet Automation Support","estimated_value":700,"status":"new","notes":"Large remote Excel hiring volume indicates recurring global demand. Outreach angle: position as overflow automation vendor for teams posting repetitive Excel roles. URL: https://in.linkedin.com/jobs/work-from-home-excel-jobs"},
{"id":"sprint-20260304-023","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Excel VBA Freelance Jobs (France)","service":"VBA Automation Projects","estimated_value":850,"status":"new","notes":"Niche VBA freelance feed suggests active buyers with legacy spreadsheet systems. Outreach angle: offer modernization path from brittle VBA to maintainable hybrid workflows. URL: https://fr.linkedin.com/jobs/expert-excel-vba-freelance-emplois"},
{"id":"sprint-20260304-024","date":"2026-03-04","source":"LinkedIn","client":"LinkedIn Excel VBA Jobs Feed (France)","service":"Legacy Excel Process Optimization","estimated_value":850,"status":"new","notes":"Feed highlights multiple fresh VBA postings including freelance contexts. Outreach angle: sell quick audit + stabilization sprint for error-prone VBA workbooks. URL: https://fr.linkedin.com/jobs/excel-vba-emplois"},
{"id":"sprint-20260304-025","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Phoenix Bookkeeping Specialists","service":"Bookkeeping Workflow Automation","estimated_value":650,"status":"new","notes":"Bookkeeping shop with unclaimed Yelp marker and visible phone (602) 400-5383; likely heavy recurring spreadsheet tasks. Outreach angle: automate monthly close checklist + client reporting templates. URL: https://www.yelp.com/biz/phoenix-bookkeeping-specialists-phoenix"},
{"id":"sprint-20260304-026","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Serenity Bookkeeping & Payroll Services","service":"Payroll + Reconciliation Automation","estimated_value":700,"status":"new","notes":"Small bookkeeping/payroll operation; high probability of manual reconciliation burden. Outreach angle: propose payroll reconciliation workbook with exception flags and audit trail tabs. URL: https://www.yelp.com/biz/serenity-bookkeeping-and-payroll-services-phoenix"},
{"id":"sprint-20260304-027","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Kufner Bookkeeping Services","service":"Recurring Client Reporting Automation","estimated_value":650,"status":"new","notes":"Bookkeeping service with phone shown (602) 513-2797; likely multi-client monthly reporting workflows. Outreach angle: standardized reporting pack + one-click export dashboards. URL: https://www.yelp.com/biz/kufner-bookkeeping-services-phoenix-2"},
{"id":"sprint-20260304-028","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Kore Bookkeeping Solutions","service":"Small Business Spreadsheet Ops","estimated_value":600,"status":"new","notes":"Bookkeeper listing with direct number (480) 818-5673. Outreach angle: automate AP/AR trackers and overdue alerts to reduce admin hours. URL: https://www.yelp.com/biz/kore-bookkeeping-solutions-phoenix"},
{"id":"sprint-20260304-029","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Top Tax Services (Seattle)","service":"Tax Prep Data Intake Automation","estimated_value":750,"status":"new","notes":"Tax service listing includes phone (206) 779-7456 and small-business focus; tax firms often juggle manual intake sheets. Outreach angle: client intake + document status dashboard in Excel/Sheets. URL: https://www.yelp.com/biz/top-tax-services-seattle-2"},
{"id":"sprint-20260304-030","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Fortis Medical Billing","service":"Medical Billing Spreadsheet Automation","estimated_value":900,"status":"new","notes":"Medical billing company with phone (214) 571-7163; claims and follow-up tracking are spreadsheet-heavy. Outreach angle: build denial tracking + aging dashboard + weekly KPI automation. URL: https://www.yelp.com/biz/fortis-medical-billing-dallas"}
]

path = r"C:\Users\chead\.openclaw\workspace-john\leads.jsonl"
with open(path, "a", encoding="utf-8") as f:
    for e in entries:
        f.write(json.dumps(e, ensure_ascii=False) + "\n")

print(f"appended {len(entries)} leads")
