import json, pathlib
p = pathlib.Path('C:/Users/chead/.openclaw/workspace-john/leads.jsonl')
entries = [
{"id":"sprint39-001","date":"2026-03-04","source":"Fiverr","client":"yasirhamedca","service":"Excel VBA + Automation","estimated_value":300,"status":"new","url":"https://www.fiverr.com/yasirhamedca/do-excel-macro-excel-automation-vba-data-cleaning-dashboard-formulas-table","notes":"Fiverr seller offering Excel macro/automation; outreach angle: propose white-label overflow partnership for US SMB Excel cleanup + dashboard projects."},
{"id":"sprint39-002","date":"2026-03-04","source":"Fiverr","client":"ajittomar","service":"Excel VBA Automation","estimated_value":350,"status":"new","url":"https://www.fiverr.com/ajittomar/prepare-an-excel-data-spreadsheet","notes":"Mentions fast data-processing automation; outreach angle: pitch subcontracting recurring spreadsheet automation tasks with fixed weekly volume."},
{"id":"sprint39-003","date":"2026-03-04","source":"Fiverr","client":"luckdomini","service":"Excel Automation (TypeScript/VBA)","estimated_value":250,"status":"new","url":"https://www.fiverr.com/luckdomini/do-excel-automation-with-typescript-and-visual-basic-vba","notes":"Low-ticket automation offer suggests high responsiveness; outreach angle: recruit as rapid-turnaround backend resource for micro-automation requests."},
{"id":"sprint39-004","date":"2026-03-04","source":"Fiverr","client":"ayesha0268","service":"Excel/Google Sheets Automation","estimated_value":250,"status":"new","url":"https://www.fiverr.com/ayesha0268/do-excel-vba-macro-formula-automation-and-google-spreadsheet","notes":"Broad Excel + Sheets scope; outreach angle: partner on formula rescue and workbook stabilization jobs NorthStar closes via outreach."},
{"id":"sprint39-005","date":"2026-03-04","source":"Fiverr","client":"mabidsherazi","service":"Excel Automation + Web Scraping","estimated_value":400,"status":"new","url":"https://www.fiverr.com/mabidsherazi/do-excel-formulas-automation-with-vba-and-python-inventory-management-pos","notes":"Combines scraping + inventory workflows; outreach angle: pitch fulfillment support for lead-list enrichment and inventory reporting automations."},
{"id":"sprint39-006","date":"2026-03-04","source":"Fiverr","client":"hilalabdul","service":"AI API + Excel Integration","estimated_value":500,"status":"new","url":"https://www.fiverr.com/hilalabdul/do-api-excel-integration","notes":"AI API integration inside Excel is high-value niche; outreach angle: co-deliver premium AI-assisted spreadsheet automation retainers."},
{"id":"sprint39-007","date":"2026-03-04","source":"Upwork","client":"Excel Automation Expert Needed for VBA or Power Automate","service":"Excel Workflow Automation","estimated_value":900,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Excel-Automation-Expert-Needed-for-VBA-Power-Automate_~022000648293993351761/","notes":"Active buyer intent for automation specialist; outreach angle: offer rapid audit + 72-hour pilot to replace repetitive manual steps."},
{"id":"sprint39-008","date":"2026-03-04","source":"Upwork","client":"MS Project + Excel Automation Specialist","service":"Project Reporting Automation","estimated_value":1100,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Project-Excel-Automation-Specialist_~021993267236858798718/","notes":"Needs PM + Excel integration support; outreach angle: sell executive dashboard + status roll-up automation for operations teams."},
{"id":"sprint39-009","date":"2026-03-04","source":"Upwork","client":"Advanced Excel Automation Merging 100k+ Rows via Power Query","service":"Power Query Data Pipeline","estimated_value":1200,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Advanced-Excel-Automation-Merging-100k-Rows-via-Power-Query_~022027410762982737346/","notes":"Large data merge pain point indicates urgent ops bottleneck; outreach angle: propose robust import pipeline with validation and error logs."},
{"id":"sprint39-010","date":"2026-03-04","source":"Upwork","client":"Excel Automation Expert Needed for Data Entry Automation","service":"Data Entry Automation","estimated_value":850,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Excel-Automation-Expert-Needed-for-Data-Entry-Automation_~022014356450369286301/","notes":"Manual-entry reduction request; outreach angle: offer macro-first workflow that cuts labor hours and improves data consistency."},
{"id":"sprint39-011","date":"2026-03-04","source":"Upwork","client":"Excel Task Management Automation in n8n","service":"Excel + n8n Automation","estimated_value":1300,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Excel-Task-Management-Automation-n8n_~021905268104731035208/","notes":"Cross-tool automation requirement suggests ongoing needs; outreach angle: sell monthly automation maintenance retainer."},
{"id":"sprint39-012","date":"2026-03-04","source":"Upwork","client":"Excel Automation Expert Needed Build Fast Reliable VBA Data Processing","service":"VBA Processing System","estimated_value":1250,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Excel-Automation-Expert-Needed-Build-Fast-Reliable-VBA-Data-Processing-Systemst_~021997919851372488723/","notes":"Buyer emphasizes speed + reliability; outreach angle: position NorthStar as process hardening partner with QA checkpoints."},
{"id":"sprint39-013","date":"2026-03-04","source":"Upwork","client":"API Integration, Web Scraping, Excel Automation","service":"Data Integration Automation","estimated_value":1400,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/API-integration-Web-Scraping-Excel-Automation_~01934ab526100b419f/","notes":"Multi-source data requirement with scraping/API; outreach angle: pitch end-to-end ETL-to-Excel automation stack and monitoring."},
{"id":"sprint39-014","date":"2026-03-04","source":"Upwork","client":"Excel NetSuite Automation Specialist Needed","service":"ERP to Excel Automation","estimated_value":1500,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Excel-NetSuite-Automation-Specialist-Needed_~021858647777142354510/","notes":"ERP-connected spreadsheet automation is premium budget territory; outreach angle: offer reconciled financial/ops reporting automation package."},
{"id":"sprint39-015","date":"2026-03-04","source":"Reddit-r/slavelabour","client":"[TASK] Separate Information in an Excel File $15","service":"Excel Data Structuring","estimated_value":350,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1fhff21/task_separate_information_in_an_excel_file_15/","notes":"Poster has recurring category-splitting workload; outreach angle: propose reusable template/macros for repeated monthly separation tasks."},
{"id":"sprint39-016","date":"2026-03-04","source":"Reddit-r/slavelabour","client":"[Task] Export Excel Company location on interactive map","service":"Excel + Mapping Workflow","estimated_value":500,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1di6xdo/task_export_excel_company_location_on_interactive/","notes":"Geo-mapping from spreadsheet indicates business ops need; outreach angle: offer automated geocoding + dashboard map refresh workflow."},
{"id":"sprint39-017","date":"2026-03-04","source":"Reddit-r/slavelabour","client":"[TASK] Convert PDF to Excel","service":"PDF-to-Excel Cleanup","estimated_value":400,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1gpz4kq/task_convert_pdf_to_excel/","notes":"2500-row conversion pain implies recurring document ingestion; outreach angle: sell repeatable import+cleanup script with QA rules."},
{"id":"sprint39-018","date":"2026-03-04","source":"Reddit-r/forhire","client":"[Hiring] Excel Expert Needed: Build Custom Search Function","service":"Excel UX + Search Automation","estimated_value":650,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1gofhqq/hiring_excel_expert_needed_build_custom_search/","notes":"Needs custom find/filter usability improvements; outreach angle: package searchable interface + protected workflow for non-technical staff."},
{"id":"sprint39-019","date":"2026-03-04","source":"Reddit-r/forhire","client":"[Hiring] Looking for VBA/Excel Expert $30","service":"VBA Task Automation","estimated_value":600,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1ibg5aw/hiring_online_looking_for_vba_excel_expert_must/","notes":"Poster signals more work after trust established; outreach angle: win with quick turnaround then upsell bundled automation backlog."},
{"id":"sprint39-020","date":"2026-03-04","source":"Reddit-r/forhire","client":"[Hiring] Someone who can make an excel sheet for scheduling","service":"Scheduling Automation","estimated_value":700,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1aizmuz/hiring_someone_who_can_make_an_excel_sheet_for/","notes":"Scheduling + function-heavy sheet usually expands into full ops tracker; outreach angle: offer scheduler plus utilization/forecast tabs."},
{"id":"sprint39-021","date":"2026-03-04","source":"LinkedIn","client":"Zoe Burkland - Burkland Bookkeeping LLC","service":"Bookkeeping Workflow Automation","estimated_value":900,"status":"new","url":"https://www.linkedin.com/in/burklandbookkeeping/","notes":"Seattle-area bookkeeping owner likely managing repetitive monthly close workflows; outreach angle: automate categorization/reconciliation trackers."},
{"id":"sprint39-022","date":"2026-03-04","source":"LinkedIn","client":"Oghale Agbro - AOA Bookkeeping, LLC","service":"Client Reporting Automation","estimated_value":1000,"status":"new","url":"https://www.linkedin.com/in/oghaleagbro/","notes":"Bookkeeping operator with growth potential; outreach angle: build standardized KPI workbook templates to speed client reporting cadence."},
{"id":"sprint39-023","date":"2026-03-04","source":"LinkedIn","client":"Courtney Day - Day By Day Bookkeeping, LLC","service":"Excel + QuickBooks Export Automation","estimated_value":950,"status":"new","url":"https://www.linkedin.com/in/courtday/","notes":"Small-firm owner in Greater Seattle; outreach angle: automate bank export cleanup and month-end workbook generation."},
{"id":"sprint39-024","date":"2026-03-04","source":"LinkedIn","client":"Jason Allenberg - Ballinger Landscaping","service":"Landscape Ops Dashboard","estimated_value":1200,"status":"new","url":"https://www.linkedin.com/in/jasonallenberg/","notes":"Handles many residential/commercial accounts; outreach angle: create job scheduling + route profitability dashboard from field data."},
{"id":"sprint39-025","date":"2026-03-04","source":"LinkedIn","client":"Josh Herrera - Joshua's Landscaping","service":"Estimate + Job Costing Automation","estimated_value":1100,"status":"new","url":"https://www.linkedin.com/in/josh-herrera-0305b3104/","notes":"Owner-operator profile suggests manual estimating/admin burden; outreach angle: deploy quote-to-invoice tracker with auto-margin calculations."},
{"id":"sprint39-026","date":"2026-03-04","source":"LinkedIn","client":"Cesar Tello - Green Seattle Landscaping Service","service":"Lead-to-Schedule Spreadsheet System","estimated_value":1000,"status":"new","url":"https://www.linkedin.com/in/cesar-tello-241026357/","notes":"Small local landscaping business likely early-stage systems; outreach angle: implement simple CRM + scheduling workbook for faster follow-up."},
{"id":"sprint39-027","date":"2026-03-04","source":"Local SMB (Yelp)","client":"My Seattle Bookkeeper","service":"Bookkeeping Process Automation","estimated_value":850,"status":"new","url":"https://www.yelp.com/biz/my-seattle-bookkeeper-seattle","notes":"Local bookkeeping shop with broad service menu; outreach angle: reduce monthly close time through reusable Excel reconciliation automations."},
{"id":"sprint39-028","date":"2026-03-04","source":"Local SMB (Yelp)","client":"Efficient Bookkeeping Services","service":"Multi-client Spreadsheet Standardization","estimated_value":950,"status":"new","url":"https://www.yelp.com/biz/efficient-bookkeeping-services-seattle-3","notes":"Targets small-to-midsize/multi-unit businesses; outreach angle: standardize workbook stack and automate recurring reporting deliverables."},
{"id":"sprint39-029","date":"2026-03-04","source":"Local SMB (Yelp)","client":"System Six: Strategic Bookkeeping & Analysis","service":"Advanced Financial Dashboarding","estimated_value":1300,"status":"new","url":"https://www.yelp.com/biz/system-six-strategic-bookkeeping-and-analysis-seattle","notes":"Advisory-style bookkeeping firm can monetize premium dashboards; outreach angle: white-label CFO dashboard templates for client upsells."},
{"id":"sprint39-030","date":"2026-03-04","source":"Local SMB (Yelp)","client":"MC Bookkeeping and Tax","service":"Tax Season Data Workflow Automation","estimated_value":1100,"status":"new","url":"https://www.yelp.com/biz/mc-bookkeeping-and-tax-seattle","notes":"Bookkeeping + tax workflow likely bottlenecked during filing season; outreach angle: automate organizer intake and prep-status tracking."}
]
with p.open('a', encoding='utf-8') as f:
    for e in entries:
        f.write(json.dumps(e, ensure_ascii=False) + '\n')
print('appended', len(entries))
