import json
p=r"C:\Users\chead\.openclaw\workspace-john\leads.jsonl"
with open(p,encoding='utf-8',errors='ignore') as f:
    existing=[]\nfor l in f:\n    s=l.strip()\n    if not s: continue\n    try:\n        existing.append(json.loads(s))\n    except Exception:\n        continue
keys={(e.get('client','').strip().lower(), e.get('url','').strip().lower()) for e in existing}
new=[]
new.append({"id":"sprint11-001","date":"2026-03-04","source":"Fiverr","client":"aamir_453","contact_name":"","phone":"","email":"","location":"Online","service":"Excel automation spreadsheet build","estimated_value":250,"status":"new","url":"https://www.fiverr.com/aamir_453/design-beautiful-excel-spreadsheet-with-formulas-automation-pivot-table","notes":"Outreach angle: white-label overflow + referral swap for spreadsheet automation gigs; position as US-facing delivery partner for faster turnaround."})
new.append({"id":"sprint11-002","date":"2026-03-04","source":"Fiverr","client":"hilalabdul","contact_name":"","phone":"","email":"","location":"Online","service":"API-to-Excel workflow automation","estimated_value":400,"status":"new","url":"https://www.fiverr.com/hilalabdul/do-api-excel-integration","notes":"Outreach angle: co-delivery on API + Sheets projects for SMB ops teams; offer backend automation support under their brand."})
new.append({"id":"sprint11-003","date":"2026-03-04","source":"Fiverr","client":"talmeez_89","contact_name":"","phone":"","email":"","location":"Online","service":"Automated Excel scheduling/reporting sheets","estimated_value":220,"status":"new","url":"https://www.fiverr.com/talmeez_89/create-an-automated-microsoft-excel-spreadsheet-formula","notes":"Outreach angle: partner for complex formula/dashboard jobs they may underserve; propose rev-share on handoff leads."})
new.append({"id":"sprint11-004","date":"2026-03-04","source":"Fiverr","client":"ajittomar","contact_name":"","phone":"","email":"","location":"Online","service":"Excel VBA process automation","estimated_value":500,"status":"new","url":"https://www.fiverr.com/ajittomar/prepare-an-excel-data-spreadsheet","notes":"Outreach angle: overflow support for VBA-heavy client requests; emphasize QA, documentation, and 24h bug-fix turnaround."})
new.append({"id":"sprint11-005","date":"2026-03-04","source":"Fiverr","client":"azcodes07","contact_name":"","phone":"","email":"","location":"Online","service":"Python + Excel dashboard automation","estimated_value":450,"status":"new","url":"https://www.fiverr.com/azcodes07/do-excel-analysis-and-web-automation-in-python","notes":"Outreach angle: team-up on Python data pipelines feeding Excel dashboards for SMB reporting."})
new.append({"id":"sprint11-006","date":"2026-03-04","source":"Fiverr","client":"caiojunger","contact_name":"","phone":"","email":"","location":"Online","service":"Power Query data cleanup automation","estimated_value":300,"status":"new","url":"https://www.fiverr.com/caiojunger/automate-power-query-to-clean-data","notes":"Outreach angle: cross-referral for Power Query cleanup + downstream KPI dashboard projects."})
new.append({"id":"sprint11-007","date":"2026-03-04","source":"Upwork","client":"Data Entry Specialist for Excel and Web Research (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Excel data entry process automation","estimated_value":350,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Data-Entry-Specialist-for-Excel-and-Web-Research_~022027693087997269852/","notes":"Outreach angle: replace manual entry with template + validation macros to cut handling time and errors."})
new.append({"id":"sprint11-008","date":"2026-03-04","source":"Upwork","client":"Building Excel Dashboard - Data Organization (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Interactive Excel dashboard build","estimated_value":700,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Building-Excel-Dashboard-Data-Organization_~021958520624356574133/","notes":"Outreach angle: offer quick MVP dashboard in 48h + iterative improvements from real usage."})
new.append({"id":"sprint11-009","date":"2026-03-04","source":"Upwork","client":"TREKKA Suite Sheets/Excel Expert Hiring (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Digital spreadsheet product development","estimated_value":1200,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Hiring-Google-Sheets-Excel-Expert-for-Digital-Products-TREKKA-Suite_~022006060552316597482/","notes":"Outreach angle: productize premium templates with automation hooks; upsell maintenance and customer support workflows."})
new.append({"id":"sprint11-010","date":"2026-03-04","source":"Upwork","client":"Create Excel Dashboard for Retail Shop (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Retail sales/inventory dashboard automation","estimated_value":450,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Create-Excel-Dashboard-for-Retail-Shop_~021954496230415473101/","notes":"Outreach angle: connect POS exports to auto-refresh dashboard with reorder and margin alerts."})
new.append({"id":"sprint11-011","date":"2026-03-04","source":"Upwork","client":"Finance + QuickBooks + Excel Integration (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Excel-QuickBooks KPI integration","estimated_value":1500,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Finance-QuickBooks-Excel-Expert-Needed-for-Accounting-Integration_~021956994761362534567/","notes":"Outreach angle: build finance ops cockpit syncing Sheets/Excel + QBO for pricing/SKU decisions."})
new.append({"id":"sprint11-012","date":"2026-03-04","source":"Upwork","client":"Google Apps Script & Sheets Automation (Job Poster)","contact_name":"","phone":"","email":"","location":"Remote","service":"Google Sheets workflow automation","estimated_value":900,"status":"new","url":"https://www.upwork.com/freelance-jobs/apply/Google-App-Scripts-Google-Sheets-Automation-Expert-Needed_~021956158046159154118/","notes":"Outreach angle: identify top 2 repetitive workflows and automate end-to-end with audit logs and handoff docs."})
new.append({"id":"sprint11-013","date":"2026-03-04","source":"Reddit","client":"u/1mgonir - Urgent Excel Rate Adjustment Poster","contact_name":"","phone":"","email":"","location":"Online","service":"Excel pricing adjustment model","estimated_value":200,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1mgonir/urgent_help_needed_excel_rate_adjustment_keep/","notes":"Outreach angle: urgent rescue + reusable pricing template to prevent repeat manual recalculations."})
new.append({"id":"sprint11-014","date":"2026-03-04","source":"Reddit","client":"u/1aizmuz - Scheduling Sheet Hiring Poster","contact_name":"","phone":"","email":"","location":"Online","service":"Custom Excel scheduling system","estimated_value":400,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1aizmuz/hiring_someone_who_can_make_an_excel_sheet_for/","notes":"Outreach angle: deliver scheduling sheet with conflict checks, shift views, and simple admin controls."})
new.append({"id":"sprint11-015","date":"2026-03-04","source":"Reddit","client":"u/1gofhqq - Excel Search Function Hiring Poster","contact_name":"","phone":"","email":"","location":"Online","service":"Advanced Excel data filtering/search tool","estimated_value":350,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1gofhqq/hiring_excel_expert_needed_build_custom_search/","notes":"Outreach angle: build fast search UX with named ranges + optional VBA for one-click filtering."})
new.append({"id":"sprint11-016","date":"2026-03-04","source":"Reddit","client":"u/1ibg5aw - VBA/Excel Expert Hiring Poster","contact_name":"","phone":"","email":"","location":"Online","service":"VBA automation + ongoing support","estimated_value":600,"status":"new","url":"https://www.reddit.com/r/forhire/comments/1ibg5aw/hiring_online_looking_for_vba_excel_expert_must/","notes":"Outreach angle: position for long-term retainer since poster mentions more work if speed/trust is proven."})
new.append({"id":"sprint11-017","date":"2026-03-04","source":"Reddit","client":"u/1fhff21 - Excel File Separation Task Poster","contact_name":"","phone":"","email":"","location":"Online","service":"Excel categorization automation","estimated_value":180,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1fhff21/task_separate_information_in_an_excel_file_15/","notes":"Outreach angle: solve immediate split task and upsell macro button for recurring category separation."})
new.append({"id":"sprint11-018","date":"2026-03-04","source":"Reddit","client":"u/1gpz4kq - PDF to Excel Conversion Poster","contact_name":"","phone":"","email":"","location":"Online","service":"PDF-to-Excel cleanup pipeline","estimated_value":300,"status":"new","url":"https://www.reddit.com/r/slavelabour/comments/1gpz4kq/task_convert_pdf_to_excel/","notes":"Outreach angle: automate PDF import cleanup to handle split-row errors at scale for future files."})
new.append({"id":"sprint11-019","date":"2026-03-04","source":"LinkedIn","client":"Sharla Clark","contact_name":"Sharla Clark","phone":"","email":"","location":"Dallas-Fort Worth Metroplex","service":"Bookkeeping workflow automation","estimated_value":900,"status":"new","url":"https://www.linkedin.com/in/bloombooks/","notes":"Outreach angle: help Bloom Bookkeeping automate recurring monthly close workpapers + client reporting packs."})
new.append({"id":"sprint11-020","date":"2026-03-04","source":"LinkedIn","client":"Stefani Vazquez","contact_name":"Stefani Vazquez","phone":"","email":"","location":"Dallas, TX","service":"Bookkeeping pipeline dashboards","estimated_value":800,"status":"new","url":"https://www.linkedin.com/in/svbookkeepingsolutions/","notes":"Outreach angle: build KPI dashboard for AR/AP turnaround and service capacity planning."})
new.append({"id":"sprint11-021","date":"2026-03-04","source":"LinkedIn","client":"Stacey Baer","contact_name":"Stacey Baer","phone":"","email":"","location":"Dallas, TX","service":"Small-business bookkeeping automation","estimated_value":950,"status":"new","url":"https://www.linkedin.com/in/stacey-baer-a0615a1b/","notes":"Outreach angle: propose standardized import templates and exception reporting to reduce manual cleanup."})
new.append({"id":"sprint11-022","date":"2026-03-04","source":"LinkedIn","client":"Kelsey Burks","contact_name":"Kelsey Burks","phone":"","email":"","location":"Dallas-Fort Worth Metroplex","service":"Profitability reporting automation","estimated_value":850,"status":"new","url":"https://www.linkedin.com/in/kelsey-burks-92067476/","notes":"Outreach angle: automate client profitability snapshots and month-end owner reports."})
new.append({"id":"sprint11-023","date":"2026-03-04","source":"LinkedIn","client":"Michael Benson","contact_name":"Michael Benson","phone":"","email":"","location":"Texas","service":"Plumbing ops spreadsheet automation","estimated_value":1100,"status":"new","url":"https://www.linkedin.com/in/michael-benson-2433b512a/","notes":"Outreach angle: dispatch + invoice tracking dashboard for field plumbing jobs to tighten cash cycle."})
new.append({"id":"sprint11-024","date":"2026-03-04","source":"LinkedIn","client":"Travis Mayorga","contact_name":"Travis Mayorga","phone":"","email":"","location":"San Antonio, TX","service":"Service business KPI dashboard","estimated_value":1000,"status":"new","url":"https://www.linkedin.com/in/travis-mayorga-09391429/","notes":"Outreach angle: automate job-costing and technician productivity reporting from existing spreadsheets."})
new.append({"id":"sprint11-025","date":"2026-03-04","source":"Yelp","client":"Dallas Tax and Books","contact_name":"","phone":"(214) 353-0654","email":"","location":"Dallas, TX","service":"Tax/bookkeeping reporting automation","estimated_value":900,"status":"new","url":"https://www.yelp.com/biz/crescere-group-dallas","notes":"Local SMB niche: tax+bookkeeping shop; likely high-volume repetitive reconciliations and client report prep."})
new.append({"id":"sprint11-026","date":"2026-03-04","source":"Yelp","client":"Smart Books Bookkeeping","contact_name":"","phone":"","email":"","location":"Mansfield, TX","service":"Bookkeeping process automation","estimated_value":750,"status":"new","url":"https://www.yelp.com/biz/smart-books-bookkeeping-mansfield","notes":"Local SMB niche: bookkeeping service likely managing recurring imports, categorization, and monthly exports."})
new.append({"id":"sprint11-027","date":"2026-03-04","source":"Yelp","client":"The Bookkeeping Bee","contact_name":"","phone":"","email":"","location":"Farmers Branch, TX","service":"Payroll/bookkeeping workflow automation","estimated_value":800,"status":"new","url":"https://www.yelp.com/biz/the-bookkeeping-bee-farmers-branch","notes":"Local SMB niche: payroll + bookkeeping automation opportunity for standardized templates and QA checks."})
new.append({"id":"sprint11-028","date":"2026-03-04","source":"Yelp","client":"Leeper Bookkeeping Service","contact_name":"","phone":"","email":"","location":"Plano, TX","service":"SMB bookkeeping dashboard + automation","estimated_value":1000,"status":"new","url":"https://www.yelp.com/biz/leeper-bookkeeping-service-plano","notes":"Local SMB niche: explicitly serves small/mid businesses; pitch monthly close automation + KPI client portals."})
new.append({"id":"sprint11-029","date":"2026-03-04","source":"Yelp","client":"Ana Garza Tax Services","contact_name":"Ana M Garza","phone":"","email":"","location":"Garland, TX","service":"Tax office spreadsheet automation","estimated_value":850,"status":"new","url":"https://www.yelp.com/biz/ana-garza-tax-services-garland","notes":"Local SMB niche: multi-service office (tax, payroll, bookkeeping) with clear potential for workflow standardization."})
new.append({"id":"sprint11-030","date":"2026-03-04","source":"Yelp","client":"Erin Armstrong - Business Advisor & CFO","contact_name":"Erin Armstrong","phone":"","email":"","location":"Dallas, TX","service":"Fractional CFO reporting stack automation","estimated_value":1200,"status":"new","url":"https://www.yelp.com/biz/erin-armstrong-business-advisor-and-cfo-dallas","notes":"Local SMB niche: advisory/CFO model; outreach around automated finance packs and KPI rollups for client accounts."})
add=[]
for e in new:
    k=(e['client'].strip().lower(), e['url'].strip().lower())
    if k not in keys:
        add.append(e)
        keys.add(k)
with open(p,'a',encoding='utf-8') as f:
    for e in add:
        f.write(json.dumps(e,ensure_ascii=False)+'\n')
print('appended',len(add))
