import type { Restaurant } from "@/types/restaurant";

// ============================================================
// BITE RESTAURANT — Hotel Murano, Downtown Tacoma
// New American | Upscale Casual | Breakfast & Dinner
// ============================================================
export const biteRestaurant: Restaurant = {
  id: "bite-restaurant-tacoma",
  name: "bite Restaurant",
  slug: "bite-restaurant-tacoma",
  tagline: "Pacific Northwest Cuisine at Hotel Murano",
  description:
    "Located inside Tacoma's iconic Hotel Murano, bite brings the best of Pacific Northwest ingredients to your plate. Our kitchen sources from local farms and fishers to craft seasonal menus that celebrate the bounty of Washington State. From our signature Spanish Omelet at breakfast to seared sockeye salmon at dinner, every dish is made with care and served in an atmosphere surrounded by world-class glass art.",
  cuisine: ["american", "seafood"],
  type: "casual-dining",
  contact: {
    phone: "(253) 591-4151",
    email: "dining@hotelmuranotacoma.com",
  },
  hours: [
    { day: "monday", open: "06:30", close: "22:00", closed: false },
    { day: "tuesday", open: "06:30", close: "22:00", closed: false },
    { day: "wednesday", open: "06:30", close: "22:00", closed: false },
    { day: "thursday", open: "06:30", close: "22:00", closed: false },
    { day: "friday", open: "06:30", close: "22:00", closed: false },
    { day: "saturday", open: "07:00", close: "22:00", closed: false },
    { day: "sunday", open: "07:00", close: "21:00", closed: false },
  ],
  location: {
    address: "1320 Broadway",
    city: "Tacoma",
    state: "WA",
    zip: "98402",
    lat: 47.2529,
    lng: -122.4443,
    isFixed: true,
  },
  branding: {
    primaryColor: "#1c1c1c",
    secondaryColor: "#2a2a2a",
    accentColor: "#c9a96e",
    backgroundColor: "#faf8f5",
    textColor: "#1c1c1c",
    fontHeading: "Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1920&q=80",
    template: "casual-dining",
  },
  socialMedia: {
    instagram: "https://instagram.com/hotelmuranotacoma",
    facebook: "https://facebook.com/HotelMurano",
    yelp: "https://yelp.com/biz/bite-restaurant-tacoma",
    googleBusinessUrl: "https://g.page/biterestauranttacoma",
  },
  features: {
    tier: "growth",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: true,
    giftCards: false,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: true,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: false,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.3,
    totalReviews: 163,
    googleRating: 4.4,
    googleReviewCount: 112,
    yelpRating: 4.0,
    yelpReviewCount: 51,
    featuredReviews: [
      {
        source: "google",
        author: "Karen P.",
        rating: 5,
        text: "The seared sockeye salmon was incredible — perfectly cooked with that mango salsa on top. The atmosphere inside Hotel Murano is gorgeous with all the glass art. Felt like a special occasion even on a Tuesday.",
        date: "2 weeks ago",
      },
      {
        source: "yelp",
        author: "Marcus T.",
        rating: 5,
        text: "Best breakfast in Tacoma, hands down. The Spanish Omelet with chorizo and verde sauce is a must. Breakfast potatoes are crispy perfection. Service was warm and attentive.",
        date: "1 month ago",
      },
      {
        source: "google",
        author: "Jennifer W.",
        rating: 4,
        text: "We had the Wagyu burger and the fish and chips for dinner. Both were excellent — the burger especially. Great happy hour prices too. Only docked a star because parking downtown can be tricky.",
        date: "3 weeks ago",
      },
      {
        source: "google",
        author: "David R.",
        rating: 5,
        text: "The pork belly sliders with that Asian BBQ sauce are addictive. We ordered two rounds. The crème brulée for dessert was classic and perfectly torched. Will be back every time we stay at the Murano.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Sophia L.",
        rating: 5,
        text: "Stunning restaurant inside a stunning hotel. Had the clams linguine and it was bursting with flavor — the lemon-garlic white wine sauce was incredible. Our server recommended the tiramisu and it did not disappoint.",
        date: "2 months ago",
      },
      {
        source: "google",
        author: "Chris M.",
        rating: 4,
        text: "Great spot for a business dinner. T-bone steak was cooked perfectly medium-rare with that chimichurri butter. Reasonable prices for the quality. The crab and corn chowder is a sleeper hit.",
        date: "1 month ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-15",
    sections: [
      {
        id: "breakfast-small",
        name: "Breakfast",
        description: "Start your morning right",
        sortOrder: 1,
        isActive: true,
        availableFrom: "06:30",
        availableUntil: "11:00",
        items: [
          {
            id: "eggs-benedict",
            name: "Eggs Benedict",
            slug: "eggs-benedict",
            description: "Toasted English muffin, Cure 81 ham, poached eggs, hollandaise, and crispy breakfast potatoes.",
            price: 22.0,
            image: "https://images.unsplash.com/photo-1608039829572-9b0189f08770?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "eggs", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "spanish-omelet",
            name: "Spanish Omelet",
            slug: "spanish-omelet",
            description: "Chorizo, verde sauce, Beecher's Flagship cheddar, served with crispy breakfast potatoes.",
            price: 18.0,
            image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["eggs", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "steak-and-eggs",
            name: "Steak & Eggs",
            slug: "steak-and-eggs",
            description: "7oz grilled flat iron with chimichurri, roasted cherry tomatoes, two eggs any style, breakfast potatoes.",
            price: 24.0,
            dietary: ["gluten-free"],
            allergens: ["eggs"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "apple-cider-pancakes",
            name: "Apple Cider Pancakes",
            slug: "apple-cider-pancakes",
            description: "Three fluffy pancakes with caramelized apples and real maple syrup.",
            price: 17.0,
            image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "eggs", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "dinner-starters",
        name: "Starters",
        description: "Begin your evening",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "crab-chowder",
            name: "Crab & Corn Chowder",
            slug: "crab-corn-chowder",
            description: "Rich and creamy chowder loaded with Dungeness crab and sweet corn.",
            price: 12.0,
            image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["shellfish", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "pork-belly-sliders",
            name: "Pork Belly Sliders",
            slug: "pork-belly-sliders",
            description: "Three crispy pork belly sliders with Asian BBQ sauce and fresh slaw on brioche buns.",
            price: 17.0,
            image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "soy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "calamari",
            name: "Calamari",
            slug: "calamari",
            description: "Flash-fried with spiced breading and house romesco sauce.",
            price: 16.0,
            dietary: [],
            allergens: ["gluten", "shellfish"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "crab-artichoke-dip",
            name: "Crab & Artichoke Dip",
            slug: "crab-artichoke-dip",
            description: "Dungeness crab, parmesan cheese, and toasted baguette slices.",
            price: 17.0,
            dietary: [],
            allergens: ["shellfish", "dairy", "gluten"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "dinner-mains",
        name: "Dinner Entrees",
        description: "Pacific Northwest favorites",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "sockeye-salmon",
            name: "Seared Sockeye Salmon",
            slug: "seared-sockeye-salmon",
            description: "Wild-caught sockeye with street corn pico, mango salsa, cotija cheese, and cilantro-lime vinaigrette.",
            price: 36.0,
            image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["fish", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "wagyu-burger",
            name: "American Wagyu Burger",
            slug: "wagyu-burger",
            description: "Snake River Farms beef, lettuce, Roma tomatoes, onions, bacon relish, choice of cheese, garlic herb fries.",
            price: 23.0,
            image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "tbone-steak",
            name: "Grilled T-Bone Steak",
            slug: "grilled-tbone-steak",
            description: "16oz T-bone topped with chimichurri compound butter, smashed fried red potatoes, grilled broccolini.",
            price: 47.0,
            image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["dairy"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "clams-linguine",
            name: "Clams Linguine",
            slug: "clams-linguine",
            description: "Local clams, asparagus, tomatoes, peppadews, and lemon-garlic white wine sauce.",
            price: 25.0,
            dietary: [],
            allergens: ["gluten", "shellfish"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
          {
            id: "fish-n-chips",
            name: "Fish & Chips",
            slug: "fish-and-chips",
            description: "Two pieces of beer-battered Pacific cod, garlic herb fries, and fresh coleslaw.",
            price: 23.0,
            dietary: [],
            allergens: ["gluten", "fish"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 5,
          },
        ],
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "Sweet endings",
        sortOrder: 4,
        isActive: true,
        items: [
          {
            id: "creme-brulee",
            name: "Lemon Creme Brulee",
            slug: "creme-brulee",
            description: "Creamy custard topped with perfectly torched burnt sugar.",
            price: 9.0,
            image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=600&q=80",
            dietary: ["vegetarian", "gluten-free"],
            allergens: ["dairy", "eggs"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "tiramisu",
            name: "Tiramisu",
            slug: "tiramisu",
            description: "Espresso-soaked cake, mascarpone, white chocolate curls, and cocoa.",
            price: 9.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy", "eggs"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "chocolate-decadence",
            name: "Chocolate Decadence",
            slug: "chocolate-decadence",
            description: "Flourless dark chocolate cake with raspberry coulis. Gluten free.",
            price: 10.0,
            dietary: ["vegetarian", "gluten-free"],
            allergens: ["dairy", "eggs"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-15",
  updatedAt: "2026-03-15",
};

// ============================================================
// COOPER'S FOOD & DRINK — North Tacoma
// American Comfort | Pizza, Burgers, Brunch | Neighborhood Favorite
// ============================================================
export const coopersRestaurant: Restaurant = {
  id: "coopers-food-and-drink-tacoma",
  name: "Cooper's Food & Drink",
  slug: "coopers-food-and-drink-tacoma",
  tagline: "Your Neighborhood Spot for Great Food & Good Times",
  description:
    "Cooper's is the kind of place every neighborhood deserves — where the burgers are thick, the pizza is hand-tossed, and the patio has fire pits going year-round. Locally owned and proudly serving Tacoma's North End, we keep things honest: great ingredients, big portions, fair prices. Whether you're here for Saturday brunch, weeknight pizza, or happy hour with friends, you'll leave full and happy.",
  cuisine: ["american"],
  type: "casual-dining",
  contact: {
    phone: "(253) 503-0329",
    email: "info@cooperstacoma.com",
  },
  hours: [
    { day: "monday", open: "11:00", close: "21:00", closed: false },
    { day: "tuesday", open: "11:00", close: "21:00", closed: false },
    { day: "wednesday", open: "11:00", close: "21:00", closed: false },
    { day: "thursday", open: "11:00", close: "21:00", closed: false },
    { day: "friday", open: "11:00", close: "22:00", closed: false },
    { day: "saturday", open: "09:00", close: "22:00", closed: false },
    { day: "sunday", open: "09:00", close: "21:00", closed: false },
  ],
  location: {
    address: "5928 N 26th St",
    city: "Tacoma",
    state: "WA",
    zip: "98407",
    lat: 47.2806,
    lng: -122.4977,
    isFixed: true,
  },
  branding: {
    primaryColor: "#2d1810",
    secondaryColor: "#3d2518",
    accentColor: "#d4782f",
    backgroundColor: "#fdf6f0",
    textColor: "#2d1810",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1920&q=80",
    template: "casual-dining",
  },
  socialMedia: {
    instagram: "https://instagram.com/cooperstacoma",
    facebook: "https://facebook.com/CoopersTacoma",
    yelp: "https://yelp.com/biz/coopers-food-and-drink-tacoma",
  },
  features: {
    tier: "growth",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: true,
    giftCards: false,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: false,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: true,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.5,
    totalReviews: 525,
    googleRating: 4.5,
    googleReviewCount: 320,
    yelpRating: 4.5,
    yelpReviewCount: 205,
    featuredReviews: [
      {
        source: "google",
        author: "Amanda C.",
        rating: 5,
        text: "Best pizza in Tacoma, no question. The sweet chili Thai pulled pork pizza is unreal. The covered patio with fire pits is the move — super cozy even in winter.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Brian K.",
        rating: 5,
        text: "Cooper's is our go-to for everything. Saturday brunch is incredible — the portions are massive and the mimosas keep flowing. Staff is always friendly and remembers our names.",
        date: "2 weeks ago",
      },
      {
        source: "google",
        author: "Michelle R.",
        rating: 4,
        text: "Amazing food, big portions, and reasonable prices. The gouda mushroom flatbread was fantastic. The only downside is it gets busy on weekends, but honestly that just proves how good it is.",
        date: "1 month ago",
      },
      {
        source: "yelp",
        author: "James D.",
        rating: 5,
        text: "The Reuben here is legit — slow-roasted corned beef piled high with Swiss and sauerkraut on perfect rye. And the happy hour deals are some of the best in the North End.",
        date: "3 weeks ago",
      },
      {
        source: "google",
        author: "Taylor S.",
        rating: 5,
        text: "My family's favorite restaurant. Kids love the chicken bacon pizza, my wife loves brunch, and I love the burgers. Great draft beer selection too. Cooper's just gets it right.",
        date: "2 months ago",
      },
      {
        source: "google",
        author: "Lisa H.",
        rating: 4,
        text: "Had the nachos and the caprese sandwich — both amazing. The nachos have real pulled pork, not that sad shredded stuff. Patio vibes are incredible with the fire pits and big screens.",
        date: "1 month ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-15",
    sections: [
      {
        id: "appetizers",
        name: "Starters",
        description: "Share a few or keep them to yourself",
        sortOrder: 1,
        isActive: true,
        items: [
          {
            id: "loaded-nachos",
            name: "Loaded Nachos",
            slug: "loaded-nachos",
            description: "House-fried tortilla chips piled with olives, black beans, jalapenos, shredded cheese, salsa, and guac. Choice of pulled pork, chicken, or beef, drizzled in sour cream.",
            price: 16.0,
            image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&q=80",
            dietary: [],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "coopers-pretzel",
            name: "Cooper's Giant Pretzel",
            slug: "coopers-pretzel",
            description: "Warm, soft baked pretzel served with house beer cheese and spicy mustard.",
            price: 13.0,
            image: "https://images.unsplash.com/photo-1570563676870-aea291042244?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "bruschetta",
            name: "Caprese Bruschetta",
            slug: "caprese-bruschetta",
            description: "Toasted baguette slices topped with fresh buffalo mozzarella, sliced tomato, fresh basil, and balsamic glaze.",
            price: 14.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "pickle-spears",
            name: "Fried Pickle Spears",
            slug: "fried-pickle-spears",
            description: "Beer-battered dill pickle spears with ranch dipping sauce.",
            price: 11.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "sandwiches",
        name: "Sandwiches & Burgers",
        description: "Served with garlic herb fries",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "reuben",
            name: "Cooper's Reuben",
            slug: "coopers-reuben",
            description: "Slow-roasted corned beef, melted Swiss cheese, sauerkraut, and thousand island on toasted rye bread.",
            price: 17.0,
            image: "https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "caprese-sandwich",
            name: "Caprese Sandwich",
            slug: "caprese-sandwich",
            description: "Fresh buffalo mozzarella melted over roasted tomatoes with house chimichurri on ciabatta.",
            price: 15.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "coopers-burger",
            name: "Cooper's Classic Burger",
            slug: "coopers-classic-burger",
            description: "Half-pound hand-formed patty, lettuce, tomato, pickles, onion, and choice of cheese on a brioche bun.",
            price: 16.0,
            image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "pizza",
        name: "Hand-Tossed Pizza",
        description: "Made fresh to order",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "thai-pork-pizza",
            name: "Sweet Chili Thai Pulled Pork",
            slug: "sweet-chili-thai-pizza",
            description: "Sweet chili sauce base, slow-smoked pulled pork, pickled onions, cilantro, and sriracha drizzle.",
            price: 18.0,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",
            dietary: ["spicy"],
            allergens: ["gluten"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: 2,
            sortOrder: 1,
          },
          {
            id: "chicken-bacon-pizza",
            name: "Chicken & Bacon Ranch",
            slug: "chicken-bacon-ranch-pizza",
            description: "Alfredo and ranch base, grilled chicken, applewood bacon, and red onions.",
            price: 17.0,
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "bbq-chicken-pizza",
            name: "BBQ Chicken Flatbread",
            slug: "bbq-chicken-flatbread",
            description: "Smoky BBQ sauce, grilled chicken, red onion, cilantro, and gouda on thin crispy flatbread.",
            price: 16.0,
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "gouda-mushroom",
            name: "Gouda Mushroom Flatbread",
            slug: "gouda-mushroom-flatbread",
            description: "Roasted wild mushrooms, smoked gouda, caramelized onions, and truffle oil on flatbread.",
            price: 16.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "Save room",
        sortOrder: 4,
        isActive: true,
        items: [
          {
            id: "seasonal-cheesecake",
            name: "Seasonal Cheesecake",
            slug: "seasonal-cheesecake",
            description: "House-made cheesecake that changes with the season. Ask your server for today's flavor.",
            price: 10.0,
            image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy", "eggs"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-15",
  updatedAt: "2026-03-15",
};

// ============================================================
// LATAH BISTRO — South Hill, Spokane
// European Bistro | Farm-to-Table | Brick Oven Pizza
// ============================================================
export const latahBistroRestaurant: Restaurant = {
  id: "latah-bistro-spokane",
  name: "Latah Bistro",
  slug: "latah-bistro-spokane",
  tagline: "Farm-to-Table Bistro on Spokane's South Hill",
  description:
    "Since 2004, Latah Bistro has been Spokane's destination for seasonal, locally sourced bistro cuisine. Our chefs create menus that change with the harvest — from brick-oven pizzas with ingredients picked that morning to wagyu steaks and pan-seared scallops for date night. With an award-winning wine list, craft cocktails, and an atmosphere that's equal parts classy and comfortable, Latah is where South Hill comes to celebrate the everyday.",
  cuisine: ["french", "american"],
  type: "casual-dining",
  contact: {
    phone: "(509) 838-8338",
    email: "info@latahbistro.com",
  },
  hours: [
    { day: "monday", open: "11:00", close: "21:00", closed: false },
    { day: "tuesday", open: "11:00", close: "21:00", closed: false },
    { day: "wednesday", open: "11:00", close: "21:00", closed: false },
    { day: "thursday", open: "11:00", close: "21:00", closed: false },
    { day: "friday", open: "11:00", close: "22:00", closed: false },
    { day: "saturday", open: "11:00", close: "22:00", closed: false },
    { day: "sunday", open: "10:00", close: "21:00", closed: false },
  ],
  location: {
    address: "4241 S Cheney Spokane Rd, Suite C",
    city: "Spokane",
    state: "WA",
    zip: "99224",
    lat: 47.6183,
    lng: -117.4468,
    isFixed: true,
  },
  branding: {
    primaryColor: "#1a2332",
    secondaryColor: "#243042",
    accentColor: "#8b6f47",
    backgroundColor: "#f9f7f4",
    textColor: "#1a2332",
    fontHeading: "Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=1920&q=80",
    template: "casual-dining",
  },
  socialMedia: {
    facebook: "https://facebook.com/LatahBistro",
    yelp: "https://yelp.com/biz/latah-bistro-spokane",
    googleBusinessUrl: "https://g.page/latahbistro",
  },
  features: {
    tier: "growth",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: true,
    giftCards: false,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: true,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: false,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.5,
    totalReviews: 287,
    googleRating: 4.5,
    googleReviewCount: 198,
    yelpRating: 4.0,
    yelpReviewCount: 89,
    featuredReviews: [
      {
        source: "google",
        author: "Rachel S.",
        rating: 5,
        text: "The filet mignon was cooked to absolute perfection, and the mushroom ravioli is hands-down the best pasta I've had in Spokane. This place feels like a hidden gem every time we visit.",
        date: "2 weeks ago",
      },
      {
        source: "yelp",
        author: "Tom H.",
        rating: 5,
        text: "Latah Bistro nails the farm-to-table concept without being pretentious about it. The brick oven pizzas are incredible — we had the Pig & Fig and it was gone in minutes. Wine list is excellent too.",
        date: "1 month ago",
      },
      {
        source: "google",
        author: "Nicole M.",
        rating: 4,
        text: "Went for Restaurant Week and was blown away. The French onion soup is the real deal — rich, bubbly, and loaded with cheese. Will definitely be back at full menu prices.",
        date: "3 weeks ago",
      },
      {
        source: "google",
        author: "Kevin B.",
        rating: 5,
        text: "Date night go-to. The scallops were perfectly seared, and the cheese plate to start was incredible. Service is always attentive without being hovery. Love this place.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Diana L.",
        rating: 5,
        text: "Twenty years in Spokane and Latah is still our favorite. The seasonal menu keeps it exciting — last visit the halibut special was phenomenal. Happy hour is one of the best deals in town.",
        date: "2 months ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-15",
    sections: [
      {
        id: "snacks",
        name: "Snacks & Starters",
        description: "Perfect for sharing",
        sortOrder: 1,
        isActive: true,
        items: [
          {
            id: "french-onion-soup",
            name: "French Onion Soup",
            slug: "french-onion-soup",
            description: "Classic slow-caramelized onion soup topped with gruyere and crusty bread.",
            price: 10.0,
            image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "cheese-plate",
            name: "Artisan Cheese Plate",
            slug: "cheese-plate",
            description: "Rotating selection of local and imported cheeses with honey, preserves, and house-baked crackers.",
            price: 28.0,
            image: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&q=80",
            dietary: ["vegetarian", "gluten-free"],
            allergens: ["dairy", "nuts"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "meatballs",
            name: "House Meatballs",
            slug: "meatballs",
            description: "Braised in San Marzano tomato sauce with shaved parmesan and grilled bread.",
            price: 22.0,
            dietary: [],
            allergens: ["gluten", "dairy", "eggs"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "entrees",
        name: "Entrees",
        description: "Seasonal and locally sourced",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "filet-mignon",
            name: "Filet Mignon",
            slug: "filet-mignon",
            description: "8oz center-cut filet, red wine demi-glace, truffle whipped potatoes, seasonal vegetables.",
            price: 58.0,
            image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "mushroom-ravioli",
            name: "Wild Mushroom Ravioli",
            slug: "mushroom-ravioli",
            description: "House-made ravioli filled with foraged mushrooms, brown butter, sage, and shaved parmesan.",
            price: 28.0,
            image: "https://images.unsplash.com/photo-1587740908075-9e245070dfaa?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy", "eggs"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "halibut",
            name: "Pan-Seared Halibut",
            slug: "pan-seared-halibut",
            description: "Alaskan halibut, lemon beurre blanc, roasted fingerling potatoes, and seasonal greens.",
            price: 47.0,
            dietary: ["gluten-free"],
            allergens: ["fish", "dairy"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "scallops",
            name: "Seared Day-Boat Scallops",
            slug: "seared-scallops",
            description: "Pan-seared scallops, cauliflower puree, pancetta crisp, and herb oil.",
            price: 49.0,
            image: "https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["shellfish", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
          {
            id: "chicken",
            name: "Roasted Airline Chicken",
            slug: "roasted-chicken",
            description: "French-cut chicken breast, herb pan jus, yukon mash, and roasted root vegetables.",
            price: 33.0,
            dietary: ["gluten-free"],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 5,
          },
        ],
      },
      {
        id: "pizza",
        name: "Brick Oven Pizza",
        description: "Fired at 800 degrees",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "pig-fig-pizza",
            name: "Pig & Fig",
            slug: "pig-and-fig",
            description: "Prosciutto, fresh figs, gorgonzola, arugula, and honey drizzle.",
            price: 23.0,
            image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "margherita",
            name: "Margherita",
            slug: "margherita",
            description: "San Marzano tomato, fresh mozzarella, basil, and extra-virgin olive oil.",
            price: 19.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "pepperoni-pizza",
            name: "Pepperoni",
            slug: "pepperoni",
            description: "Cup-and-char pepperoni, mozzarella, and house red sauce on a crispy-chewy crust.",
            price: 22.0,
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-15",
  updatedAt: "2026-03-15",
};

// ============================================================
// LUNA — South Hill, Spokane
// New American | Elevated Dining | 30+ Year Landmark
// ============================================================
export const lunaRestaurant: Restaurant = {
  id: "luna-spokane",
  name: "Luna",
  slug: "luna-spokane",
  tagline: "Spokane's South Hill Dining Landmark Since 1993",
  description:
    "For over thirty years, Luna has been the heartbeat of Spokane's South Hill dining scene. Owner Aaron DeLis and Executive Chef Joe Morris are committed to traditional hospitality — real table service, seasonal menus sourced from local farms and our own garden, and the kind of attention to detail that makes every meal feel like an occasion. No QR codes, no shortcuts. Just honest, elevated cooking and genuine warmth.",
  cuisine: ["american"],
  type: "fine-dining",
  contact: {
    phone: "(509) 448-2383",
    email: "manager@lunaspokane.com",
  },
  hours: [
    { day: "monday", open: "16:00", close: "20:00", closed: false },
    { day: "tuesday", open: "16:00", close: "20:00", closed: false },
    { day: "wednesday", open: "16:00", close: "20:00", closed: false },
    { day: "thursday", open: "16:00", close: "20:00", closed: false },
    { day: "friday", open: "16:00", close: "21:00", closed: false },
    { day: "saturday", open: "16:00", close: "21:00", closed: false },
    { day: "sunday", open: "16:00", close: "20:00", closed: false },
  ],
  location: {
    address: "5620 S Perry St",
    city: "Spokane",
    state: "WA",
    zip: "99223",
    lat: 47.6137,
    lng: -117.3621,
    isFixed: true,
  },
  branding: {
    primaryColor: "#0f1923",
    secondaryColor: "#1a2a3a",
    accentColor: "#c49b63",
    backgroundColor: "#faf9f6",
    textColor: "#0f1923",
    fontHeading: "Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&q=80",
    template: "fine-dining",
  },
  socialMedia: {
    instagram: "https://instagram.com/lunaspokane",
    facebook: "https://facebook.com/LunaSpokane",
    yelp: "https://yelp.com/biz/luna-spokane-2",
    googleBusinessUrl: "https://g.page/lunaspokane",
  },
  features: {
    tier: "growth",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: true,
    giftCards: true,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: false,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: false,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.6,
    totalReviews: 478,
    googleRating: 4.6,
    googleReviewCount: 312,
    yelpRating: 4.5,
    yelpReviewCount: 166,
    featuredReviews: [
      {
        source: "google",
        author: "Stephanie W.",
        rating: 5,
        text: "Luna is the gold standard in Spokane dining. Chef Morris changes the menu every season and it's always incredible. The complimentary fresh bread alone is worth the visit. Thirty years and still the best.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Patrick O.",
        rating: 5,
        text: "Celebrated our anniversary here — the sea bass was flawless, and the crab pasta had the richest sauce I've ever tasted. Old-school service where your server actually knows the menu and cares. This is what dining should be.",
        date: "2 weeks ago",
      },
      {
        source: "google",
        author: "Maria J.",
        rating: 5,
        text: "We come to Luna every few weeks and never get tired of it. The garden bar is beautiful, the cocktails are creative, and you can tell everything is made with love. Aaron runs a tight ship.",
        date: "1 month ago",
      },
      {
        source: "google",
        author: "Robert F.",
        rating: 4,
        text: "Outstanding food and atmosphere. The corn and mushroom farro risotto was a revelation. Only minor note — book ahead on weekends, they fill up fast. But that's a testament to how good they are.",
        date: "3 weeks ago",
      },
      {
        source: "yelp",
        author: "Linda T.",
        rating: 5,
        text: "My family has been coming to Luna since it opened in '93. The quality has never dipped. Everything is locally sourced, from Casa Cano Farms to Double R Ranch. It's Spokane dining at its finest.",
        date: "2 months ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-15",
    sections: [
      {
        id: "starters",
        name: "To Start",
        description: "From our kitchen to your table",
        sortOrder: 1,
        isActive: true,
        items: [
          {
            id: "luna-board",
            name: "The Luna Board",
            slug: "luna-board",
            description: "Local cheeses, Double R Ranch beef, house-made grape jam, seasonal pickles, and grilled bread.",
            price: 24.0,
            image: "https://images.unsplash.com/photo-1541529086526-db283c563270?w=600&q=80",
            dietary: [],
            allergens: ["dairy", "gluten"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "soup-seasonal",
            name: "Seasonal Soup",
            slug: "seasonal-soup",
            description: "Chef Morris's daily creation using whatever's freshest from our farm partners.",
            price: 12.0,
            dietary: [],
            allergens: [],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "garden-salad",
            name: "Garden Salad",
            slug: "garden-salad",
            description: "Mixed greens from Casa Cano Farms, shaved vegetables, toasted seeds, and citrus vinaigrette.",
            price: 14.0,
            image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "mains",
        name: "Entrees",
        description: "Seasonal, locally sourced, made with care",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "sea-bass",
            name: "Pan-Roasted Sea Bass",
            slug: "pan-roasted-sea-bass",
            description: "Chilean sea bass, saffron risotto, broccolini, and lemon-caper beurre blanc.",
            price: 44.0,
            image: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["fish", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "crab-pasta",
            name: "Dungeness Crab Pasta",
            slug: "dungeness-crab-pasta",
            description: "House-made tagliatelle, Dungeness crab, cherry tomatoes, white wine, and fresh herbs.",
            price: 38.0,
            image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "shellfish", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "farro-risotto",
            name: "Corn & Mushroom Farro Risotto",
            slug: "farro-risotto",
            description: "Creamy farro with roasted corn, wild mushrooms, pecorino, and truffle oil.",
            price: 28.0,
            dietary: ["vegetarian"],
            allergens: ["dairy"],
            isPopular: false,
            isChefPick: true,
            isNew: true,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "double-r-steak",
            name: "Double R Ranch Ribeye",
            slug: "double-r-ranch-ribeye",
            description: "14oz bone-in ribeye from Double R Ranch, compound herb butter, roasted potatoes, seasonal vegetables.",
            price: 52.0,
            image: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
          {
            id: "chicken-cordon-bleu",
            name: "Chicken Cordon Bleu",
            slug: "chicken-cordon-bleu",
            description: "Stuffed with ham and gruyere, panko-crusted, with Dijon cream sauce and roasted asparagus.",
            price: 32.0,
            dietary: [],
            allergens: ["gluten", "dairy", "eggs"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 5,
          },
        ],
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "A sweet finish",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "chocolate-torte",
            name: "Flourless Chocolate Torte",
            slug: "chocolate-torte",
            description: "Rich dark chocolate with raspberry coulis and fresh whipped cream.",
            price: 12.0,
            image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
            dietary: ["vegetarian", "gluten-free"],
            allergens: ["dairy", "eggs"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "creme-brulee",
            name: "Vanilla Bean Creme Brulee",
            slug: "vanilla-creme-brulee",
            description: "Classic custard with Tahitian vanilla and torched sugar.",
            price: 11.0,
            dietary: ["vegetarian", "gluten-free"],
            allergens: ["dairy", "eggs"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-15",
  updatedAt: "2026-03-15",
};

// ============================================================
// LOCAL FLAVORS — South Perry, Spokane
// Sandwich Shop & Whiskey Bar | House-Smoked Meats | Family Legacy
// ============================================================
export const localFlavorsRestaurant: Restaurant = {
  id: "local-flavors-spokane",
  name: "Local Flavors",
  slug: "local-flavors-spokane",
  tagline: "House-Smoked Sandwiches & Craft Whiskey on the South Hill",
  description:
    "Local Flavors is what happens when four generations of meat-cutting expertise meets a serious passion for whiskey. Owner Steve Egger grew up in his family's legendary Egger's Meats, and every sandwich here proves it — from slow-smoked corned beef piled on a Reuben to house-cured pastrami that melts in your mouth. Pair it with a bourbon flight or one of our craft cocktails, and you've found your new neighborhood spot on South Perry.",
  cuisine: ["american"],
  type: "bar-brewery",
  contact: {
    phone: "(509) 825-1003",
  },
  hours: [
    { day: "monday", open: "12:00", close: "20:00", closed: false },
    { day: "tuesday", open: "12:00", close: "20:00", closed: false },
    { day: "wednesday", open: "12:00", close: "22:00", closed: false },
    { day: "thursday", open: "12:00", close: "22:00", closed: false },
    { day: "friday", open: "12:00", close: "22:00", closed: false },
    { day: "saturday", open: "12:00", close: "22:00", closed: false },
    { day: "sunday", open: "12:00", close: "20:00", closed: true },
  ],
  location: {
    address: "5611 S Perry St",
    city: "Spokane",
    state: "WA",
    zip: "99223",
    lat: 47.6139,
    lng: -117.3621,
    isFixed: true,
  },
  branding: {
    primaryColor: "#1e2a1e",
    secondaryColor: "#2d3a2d",
    accentColor: "#b87333",
    backgroundColor: "#faf8f5",
    textColor: "#1e2a1e",
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1920&q=80",
    template: "bar-brewery",
  },
  socialMedia: {
    facebook: "https://facebook.com/LocalFlavorSpokane",
    yelp: "https://yelp.com/biz/local-flavors-spokane",
  },
  features: {
    tier: "starter",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: false,
    giftCards: false,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: false,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: true,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.7,
    totalReviews: 48,
    googleRating: 4.8,
    googleReviewCount: 32,
    yelpRating: 4.5,
    yelpReviewCount: 16,
    featuredReviews: [
      {
        source: "google",
        author: "Jason M.",
        rating: 5,
        text: "The Reuben is the best I've ever had — and I've had a lot of Reubens. That slow-smoked corned beef is next level. Steve clearly knows his craft. The bourbon selection is impressive too.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Amber K.",
        rating: 5,
        text: "Such a cool spot on South Perry. The club sandwich is stacked high and the meat quality is unlike anything else in Spokane. Love that they source everything locally. The whiskey flights are a great deal.",
        date: "2 weeks ago",
      },
      {
        source: "google",
        author: "Ryan P.",
        rating: 5,
        text: "Finally a place that takes sandwiches seriously. The pastrami is house-smoked and you can taste the difference. Cozy vibes, friendly staff, and a whiskey wall that'll make your jaw drop.",
        date: "1 month ago",
      },
      {
        source: "google",
        author: "Kate D.",
        rating: 4,
        text: "Great new addition to the neighborhood. The grilled cheese with bacon jam is simple but perfect. Small menu, but everything on it is done right. Can't wait to try the brisket when they add it.",
        date: "3 weeks ago",
      },
      {
        source: "yelp",
        author: "Derek L.",
        rating: 5,
        text: "Went for the whiskey, stayed for the food. The Barrelhouse Old Fashioned is perfectly made, and the charcuterie board with their family's cured meats is a must. This place has soul.",
        date: "2 months ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-15",
    sections: [
      {
        id: "sandwiches",
        name: "Sandwiches",
        description: "Built on four generations of Egger family craft",
        sortOrder: 1,
        isActive: true,
        items: [
          {
            id: "reuben",
            name: "The Reuben",
            slug: "reuben",
            description: "House slow-smoked corned beef, Swiss cheese, sauerkraut, and Russian dressing on marbled rye.",
            price: 17.0,
            image: "https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "club",
            name: "The Club",
            slug: "club-sandwich",
            description: "Triple-decked slow-roasted turkey, ham, crispy bacon, iceberg lettuce, tomato, and mayo on toasted sourdough.",
            price: 16.0,
            image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "eggs"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "grilled-cheese",
            name: "Grilled Cheese & Bacon Jam",
            slug: "grilled-cheese",
            description: "Three-cheese blend with house-made bacon jam on thick-cut sourdough, griddled golden.",
            price: 14.0,
            image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&q=80",
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
          {
            id: "smoked-chicken-quesadilla",
            name: "Smoked Chicken Quesadilla",
            slug: "smoked-chicken-quesadilla",
            description: "House-smoked chicken, peppers, onions, and melted cheese in a griddled flour tortilla with salsa and sour cream.",
            price: 15.0,
            dietary: [],
            allergens: ["gluten", "dairy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "small-plates",
        name: "Small Plates",
        description: "Perfect with a drink",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "charcuterie",
            name: "Egger's Charcuterie Board",
            slug: "charcuterie-board",
            description: "Family-cured meats, local cheeses, olives, mustard, and house pickles. A tribute to four generations of Egger's craft.",
            price: 22.0,
            image: "https://images.unsplash.com/photo-1541529086526-db283c563270?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "pretzel-beer-cheese",
            name: "Pretzel & Beer Cheese",
            slug: "pretzel-beer-cheese",
            description: "Warm soft pretzel with house beer cheese dip and grainy mustard.",
            price: 12.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "garden-salad",
            name: "House Salad",
            slug: "house-salad",
            description: "Mixed greens, cherry tomatoes, cucumber, shaved red onion, and house vinaigrette.",
            price: 14.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "cocktails",
        name: "Craft Cocktails",
        description: "Handcrafted with care",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "old-fashioned",
            name: "Barrelhouse Old Fashioned",
            slug: "barrelhouse-old-fashioned",
            description: "Buffalo Trace bourbon, demerara, Angostura bitters, orange peel. Classic done right.",
            price: 14.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 1,
          },
          {
            id: "sazerac",
            name: "Distiller's Sazerac",
            slug: "distillers-sazerac",
            description: "Sazerac rye, Peychaud's bitters, absinthe rinse, lemon twist.",
            price: 15.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            sortOrder: 2,
          },
          {
            id: "derby-spire",
            name: "Derby Spire",
            slug: "derby-spire",
            description: "Old Forester bourbon, fresh lemonade, cranberry, and a mint sprig.",
            price: 13.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            sortOrder: 3,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-15",
  updatedAt: "2026-03-15",
};

// Export all wave115 restaurants
export const wave115Restaurants: Restaurant[] = [
  biteRestaurant,
  coopersRestaurant,
  latahBistroRestaurant,
  lunaRestaurant,
  localFlavorsRestaurant,
];
