import { NextRequest, NextResponse } from "next/server";
import { getTicket, updateTicket, addTicketResponse, resolveTicket } from "@/lib/support/ticket-store";

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function GET(_request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;
    const ticket = await getTicket(id);
    if (!ticket) return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
    return NextResponse.json({ ticket });
  } catch (error) {
    console.error("[Support Tickets API]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

export async function PATCH(request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;
    const body = await request.json();

    // Handle resolve
    if (body.action === "resolve") {
      const ticket = await resolveTicket(id);
      if (!ticket) return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
      return NextResponse.json({ ticket });
    }

    // Handle response
    if (body.response) {
      const ticket = await addTicketResponse(id, body.response, body.isAutoGenerated || false);
      if (!ticket) return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
      return NextResponse.json({ ticket });
    }

    // General update
    const ticket = await updateTicket(id, body);
    if (!ticket) return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
    return NextResponse.json({ ticket });
  } catch (error) {
    console.error("[Support Tickets API]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
