import type { Restaurant } from "@/types/restaurant";

export const demoRestaurant: Restaurant = {
  id: "demo-sakura-kitchen",
  name: "Sakura Kitchen",
  slug: "sakura-kitchen",
  tagline: "Authentic Japanese Cuisine in the Heart of Seattle",
  description:
    "Sakura Kitchen brings the art of traditional Japanese cooking to Seattle's vibrant dining scene. Our chefs source the freshest local ingredients and combine them with time-honored techniques passed down through generations. From hand-rolled sushi to slow-simmered ramen, every dish tells a story of craftsmanship and care.",
  cuisine: ["japanese"],
  type: "casual-dining",
  contact: {
    phone: "(206) 555-0142",
    email: "hello@sakurakitchen.com",
  },
  hours: [
    { day: "monday", open: "11:30", close: "21:30", closed: false },
    { day: "tuesday", open: "11:30", close: "21:30", closed: false },
    { day: "wednesday", open: "11:30", close: "21:30", closed: false },
    { day: "thursday", open: "11:30", close: "22:00", closed: false },
    { day: "friday", open: "11:30", close: "22:30", closed: false },
    { day: "saturday", open: "12:00", close: "22:30", closed: false },
    { day: "sunday", open: "12:00", close: "21:00", closed: false },
  ],
  location: {
    address: "1423 Pike Place",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    lat: 47.6097,
    lng: -122.3422,
    isFixed: true,
  },
  branding: {
    primaryColor: "#1a1a2e",
    secondaryColor: "#16213e",
    accentColor: "#c0392b",
    backgroundColor: "#ffffff",
    textColor: "#1a1a2e",
    fontHeading: "Georgia, serif",
    fontBody: "system-ui, sans-serif",
    heroImage: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=1920&q=80",
    template: "casual-dining",
  },
  socialMedia: {
    instagram: "https://instagram.com/sakurakitchen",
    facebook: "https://facebook.com/sakurakitchen",
    yelp: "https://yelp.com/biz/sakura-kitchen-seattle",
    googleBusinessUrl: "https://g.page/sakurakitchen",
  },
  features: {
    tier: "growth",
    onlineOrdering: true,
    loyaltyProgram: false,
    reservations: true,
    giftCards: false,
    emailMarketing: false,
    smsMarketing: false,
    qrOrdering: false,
    cateringPortal: false,
    multiLanguage: false,
    posIntegration: false,
    deliveryIntegration: false,
    foodTruckFeatures: false,
  },
  reviews: {
    averageRating: 4.7,
    totalReviews: 328,
    googleRating: 4.8,
    googleReviewCount: 214,
    yelpRating: 4.5,
    yelpReviewCount: 114,
    featuredReviews: [
      {
        source: "google",
        author: "Michelle T.",
        rating: 5,
        text: "The best ramen I've had outside of Japan. The tonkotsu broth is incredibly rich and flavorful. The staff is always friendly and the atmosphere is cozy and authentic.",
        date: "2 weeks ago",
      },
      {
        source: "yelp",
        author: "David K.",
        rating: 5,
        text: "Sakura Kitchen never disappoints. Their sushi is always fresh, the presentation is beautiful, and the portions are generous. A true gem in Pike Place.",
        date: "1 month ago",
      },
      {
        source: "google",
        author: "Sarah L.",
        rating: 4,
        text: "Amazing food and great atmosphere. The chicken katsu curry is my go-to. Only giving 4 stars because it can get crowded on weekends, but honestly that just shows how good the food is.",
        date: "3 weeks ago",
      },
      {
        source: "google",
        author: "James R.",
        rating: 5,
        text: "Finally found an authentic Japanese restaurant in Seattle. The yakitori is perfectly grilled, and their sake selection is impressive. Will definitely be coming back.",
        date: "1 week ago",
      },
      {
        source: "yelp",
        author: "Lisa M.",
        rating: 5,
        text: "We ordered the omakase and it was an incredible experience. Chef Tanaka really knows what he's doing. Every course was a work of art.",
        date: "2 months ago",
      },
      {
        source: "google",
        author: "Robert C.",
        rating: 5,
        text: "Quick lunch spot with incredible quality. The bento box is the best value in Pike Place. Fresh, delicious, and ready in minutes.",
        date: "1 month ago",
      },
    ],
  },
  menu: {
    lastUpdated: "2026-03-01",
    sections: [
      {
        id: "starters",
        name: "Starters",
        description: "Begin your journey",
        sortOrder: 1,
        isActive: true,
        items: [
          {
            id: "edamame",
            name: "Edamame",
            slug: "edamame",
            description: "Steamed soybeans with sea salt. Simple, satisfying, and perfect for sharing.",
            price: 6.5,
            image: "https://images.unsplash.com/photo-1564093497595-593b96d80571?w=600&q=80",
            dietary: ["vegan", "gluten-free"],
            allergens: ["soy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 1,
          },
          {
            id: "gyoza",
            name: "Pork Gyoza",
            slug: "pork-gyoza",
            description: "Pan-fried dumplings filled with seasoned pork and cabbage, served with house ponzu dipping sauce.",
            price: 9.5,
            image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "soy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 2,
          },
          {
            id: "takoyaki",
            name: "Takoyaki",
            slug: "takoyaki",
            description: "Crispy octopus balls topped with bonito flakes, takoyaki sauce, and kewpie mayo.",
            price: 10.0,
            dietary: [],
            allergens: ["gluten", "eggs", "shellfish"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 3,
          },
          {
            id: "miso-soup",
            name: "Miso Soup",
            slug: "miso-soup",
            description: "Traditional white miso broth with silken tofu, wakame seaweed, and scallions.",
            price: 4.5,
            dietary: ["vegetarian"],
            allergens: ["soy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "sushi-sashimi",
        name: "Sushi & Sashimi",
        description: "Fresh from the market daily",
        sortOrder: 2,
        isActive: true,
        items: [
          {
            id: "salmon-nigiri",
            name: "Salmon Nigiri",
            slug: "salmon-nigiri",
            description: "Two pieces of fresh Atlantic salmon over seasoned sushi rice.",
            price: 8.0,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&q=80",
            dietary: ["gluten-free"],
            allergens: ["fish"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 1,
          },
          {
            id: "dragon-roll",
            name: "Dragon Roll",
            slug: "dragon-roll",
            description: "Shrimp tempura and cucumber inside, topped with avocado, eel, and sweet soy glaze.",
            price: 16.5,
            image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "shellfish", "fish", "soy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 2,
          },
          {
            id: "spicy-tuna-roll",
            name: "Spicy Tuna Roll",
            slug: "spicy-tuna-roll",
            description: "Fresh tuna with spicy mayo, cucumber, and sesame seeds. A classic with a kick.",
            price: 14.0,
            dietary: ["spicy"],
            allergens: ["fish", "soy", "sesame"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: 2,
            sortOrder: 3,
          },
          {
            id: "veggie-roll",
            name: "Garden Roll",
            slug: "garden-roll",
            description: "Avocado, cucumber, carrot, and pickled radish wrapped in soy paper.",
            price: 11.0,
            dietary: ["vegan", "gluten-free"],
            allergens: ["soy"],
            isPopular: false,
            isChefPick: false,
            isNew: true,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 4,
          },
        ],
      },
      {
        id: "ramen",
        name: "Ramen",
        description: "Slow-simmered broths, handmade noodles",
        sortOrder: 3,
        isActive: true,
        items: [
          {
            id: "tonkotsu",
            name: "Tonkotsu Ramen",
            slug: "tonkotsu-ramen",
            description: "18-hour pork bone broth, chashu pork belly, soft-boiled egg, bamboo shoots, nori, and scallions.",
            price: 17.5,
            image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "eggs", "soy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 1,
          },
          {
            id: "spicy-miso",
            name: "Spicy Miso Ramen",
            slug: "spicy-miso-ramen",
            description: "Rich miso broth with chili oil, ground pork, corn, bean sprouts, and a soft-boiled egg.",
            price: 16.5,
            dietary: ["spicy"],
            allergens: ["gluten", "eggs", "soy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: 3,
            sortOrder: 2,
          },
          {
            id: "veggie-ramen",
            name: "Vegetable Shoyu Ramen",
            slug: "vegetable-shoyu-ramen",
            description: "Mushroom and kombu dashi broth with seasonal vegetables, tofu, and handmade noodles.",
            price: 15.0,
            dietary: ["vegetarian"],
            allergens: ["gluten", "soy"],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "mains",
        name: "Mains",
        description: "Signature entrees",
        sortOrder: 4,
        isActive: true,
        items: [
          {
            id: "chicken-katsu",
            name: "Chicken Katsu Curry",
            slug: "chicken-katsu-curry",
            description: "Crispy panko-breaded chicken cutlet with house Japanese curry, steamed rice, and pickled vegetables.",
            price: 18.0,
            image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&q=80",
            dietary: [],
            allergens: ["gluten", "eggs"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: 1,
            sortOrder: 1,
          },
          {
            id: "teriyaki-salmon",
            name: "Teriyaki Salmon",
            slug: "teriyaki-salmon",
            description: "Grilled Atlantic salmon glazed with house teriyaki, served with steamed rice and sauteed seasonal greens.",
            price: 22.0,
            dietary: ["gluten-free"],
            allergens: ["fish", "soy"],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 2,
          },
          {
            id: "bento-box",
            name: "Sakura Bento Box",
            slug: "sakura-bento-box",
            description: "Chef's selection of nigiri, chicken karaage, pickled vegetables, miso soup, and rice. The best value on our menu.",
            price: 24.0,
            dietary: [],
            allergens: ["gluten", "fish", "eggs", "soy"],
            isPopular: true,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "drinks",
        name: "Drinks",
        description: "Sake, beer, tea, and more",
        sortOrder: 5,
        isActive: true,
        items: [
          {
            id: "matcha-latte",
            name: "Iced Matcha Latte",
            slug: "iced-matcha-latte",
            description: "Ceremonial-grade matcha whisked with oat milk over ice.",
            price: 6.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 1,
          },
          {
            id: "sake-flight",
            name: "Sake Flight",
            slug: "sake-flight",
            description: "Three premium sakes from different regions of Japan. Ask your server for today's selection.",
            price: 18.0,
            dietary: ["vegan", "gluten-free"],
            allergens: [],
            isPopular: false,
            isChefPick: true,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 2,
          },
          {
            id: "ramune",
            name: "Ramune Soda",
            slug: "ramune-soda",
            description: "Classic Japanese marble soda. Available in original, strawberry, and melon.",
            price: 4.0,
            dietary: ["vegan"],
            allergens: [],
            isPopular: false,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 3,
          },
        ],
      },
      {
        id: "desserts",
        name: "Desserts",
        description: "Sweet endings",
        sortOrder: 6,
        isActive: true,
        items: [
          {
            id: "mochi-ice-cream",
            name: "Mochi Ice Cream Trio",
            slug: "mochi-ice-cream-trio",
            description: "Three handmade mochi ice cream: matcha, black sesame, and strawberry.",
            price: 8.0,
            dietary: ["vegetarian"],
            allergens: ["dairy"],
            isPopular: true,
            isChefPick: false,
            isNew: false,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 1,
          },
          {
            id: "matcha-cheesecake",
            name: "Matcha Cheesecake",
            slug: "matcha-cheesecake",
            description: "Light and fluffy Japanese-style cheesecake with matcha swirl and whipped cream.",
            price: 9.0,
            dietary: ["vegetarian"],
            allergens: ["dairy", "eggs", "gluten"],
            isPopular: false,
            isChefPick: true,
            isNew: true,
            isSoldOut: false,
            spiceLevel: undefined,
            sortOrder: 2,
          },
        ],
      },
    ],
  },
  createdAt: "2026-03-05",
  updatedAt: "2026-03-05",
};
