"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import type { SupportTicket, FaqArticle, Sop } from "@/types/business";

type Tab = "tickets" | "faqs" | "sops";

const PRIORITY_CONFIG = {
  low: { label: "Low", color: "text-gray-500 bg-gray-50" },
  medium: { label: "Medium", color: "text-blue-700 bg-blue-50" },
  high: { label: "High", color: "text-amber-700 bg-amber-50" },
  urgent: { label: "Urgent", color: "text-red-700 bg-red-50" },
};

const STATUS_CONFIG = {
  open: { label: "Open", color: "text-red-700 bg-red-50" },
  in_progress: { label: "In Progress", color: "text-blue-700 bg-blue-50" },
  waiting: { label: "Waiting", color: "text-amber-700 bg-amber-50" },
  resolved: { label: "Resolved", color: "text-emerald-700 bg-emerald-50" },
  closed: { label: "Closed", color: "text-gray-500 bg-gray-100" },
};

export default function SupportPage() {
  const [tab, setTab] = useState<Tab>("tickets");
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  const [faqs, setFaqs] = useState<FaqArticle[]>([]);
  const [sops, setSops] = useState<Sop[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTicket, setSelectedTicket] = useState<SupportTicket | null>(null);

  useEffect(() => {
    Promise.all([
      fetch("/api/support/tickets").then((r) => r.json()),
      fetch("/api/support/faqs").then((r) => r.json()),
    ]).then(([ticketData, faqData]) => {
      setTickets(ticketData.tickets || []);
      setFaqs(faqData.faqs || []);
      setLoading(false);
    });
    // Load SOPs separately (no dedicated endpoint, included in faqs route for now)
  }, []);

  const resolveTicket = async (id: string) => {
    const res = await fetch(`/api/support/tickets/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "resolve" }),
    });
    if (res.ok) {
      const data = await res.json();
      setTickets((prev) => prev.map((t) => (t.id === id ? data.ticket : t)));
      setSelectedTicket(data.ticket);
    }
  };

  const sendResponse = async (id: string, message: string, isAuto: boolean) => {
    const res = await fetch(`/api/support/tickets/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ response: message, isAutoGenerated: isAuto }),
    });
    if (res.ok) {
      const data = await res.json();
      setTickets((prev) => prev.map((t) => (t.id === id ? data.ticket : t)));
      setSelectedTicket(data.ticket);
    }
  };

  if (loading) {
    return (
      <div className="p-6 animate-pulse">
        {/* Header */}
        <div className="mb-6">
          <div className="h-6 w-40 rounded bg-gray-200" />
          <div className="mt-2 h-4 w-44 rounded bg-gray-100" />
        </div>
        {/* Tab bar */}
        <div className="mb-4 flex gap-2">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="h-9 w-24 rounded-lg bg-gray-200" />
          ))}
        </div>
        {/* Ticket card placeholders */}
        <div className="space-y-3">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="rounded-xl border border-gray-200 bg-white p-4">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2">
                    <div className="h-4 w-20 rounded bg-gray-200" />
                    <div className="h-5 w-14 rounded-full bg-gray-100" />
                    <div className="h-5 w-16 rounded-full bg-gray-100" />
                  </div>
                  <div className="mt-2 h-4 w-48 rounded bg-gray-200" />
                  <div className="mt-1 h-3 w-36 rounded bg-gray-100" />
                </div>
                {i % 2 === 0 && <div className="h-5 w-32 rounded-full bg-gray-100" />}
              </div>
              <div className="mt-3 h-4 w-full rounded bg-gray-100" />
              <div className="mt-1 h-4 w-3/4 rounded bg-gray-100" />
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-xl font-bold text-gray-900">Customer Support</h1>
        <p className="text-sm text-gray-500">Tickets, FAQs, and SOPs</p>
      </div>

      {/* Tabs */}
      <div className="mb-4 flex gap-2">
        {(["tickets", "faqs", "sops"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`rounded-lg px-4 py-2 text-sm font-medium transition-all ${
              tab === t ? "bg-gray-900 text-white" : "bg-white text-gray-600 hover:bg-gray-100"
            }`}
          >
            {t === "tickets" ? `Tickets (${tickets.filter((tk) => tk.status !== "resolved" && tk.status !== "closed").length})` :
             t === "faqs" ? `FAQs (${faqs.length})` :
             `SOPs (${sops.length})`}
          </button>
        ))}
      </div>

      {/* Tickets Tab */}
      {tab === "tickets" && (
        <div className="space-y-3">
          {tickets.length === 0 ? (
            <div className="rounded-xl border border-gray-200 bg-white py-12 text-center">
              <p className="text-gray-400">No tickets yet</p>
            </div>
          ) : (
            tickets.map((ticket) => {
              const priority = PRIORITY_CONFIG[ticket.priority];
              const status = STATUS_CONFIG[ticket.status];
              return (
                <div
                  key={ticket.id}
                  onClick={() => setSelectedTicket(ticket)}
                  className="cursor-pointer rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-md"
                >
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-sm font-bold text-gray-900">{ticket.id}</span>
                        <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${priority.color}`}>{priority.label}</span>
                        <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${status.color}`}>{status.label}</span>
                      </div>
                      <h3 className="mt-1 text-sm font-semibold text-gray-900">{ticket.subject}</h3>
                      <p className="mt-0.5 text-xs text-gray-500">{ticket.clientName} &middot; {ticket.email}</p>
                    </div>
                    {ticket.autoResponse && ticket.status === "open" && (
                      <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700">
                        Auto-response ready
                      </span>
                    )}
                  </div>
                  <p className="mt-2 line-clamp-2 text-sm text-gray-600">{ticket.message}</p>
                </div>
              );
            })
          )}
        </div>
      )}

      {/* FAQs Tab */}
      {tab === "faqs" && (
        <div className="space-y-3">
          {faqs.map((faq) => (
            <div key={faq.id} className="rounded-xl border border-gray-200 bg-white p-4">
              <div className="flex items-start justify-between">
                <div>
                  <span className="mb-1 inline-block rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-500">{faq.category}</span>
                  <h3 className="text-sm font-semibold text-gray-900">{faq.question}</h3>
                </div>
              </div>
              <p className="mt-2 text-sm leading-relaxed text-gray-600">{faq.answer}</p>
              {faq.tags.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1">
                  {faq.tags.map((tag) => (
                    <span key={tag} className="rounded bg-gray-50 px-1.5 py-0.5 text-[10px] text-gray-400">{tag}</span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* SOPs Tab */}
      {tab === "sops" && (
        <div className="rounded-xl border border-gray-200 bg-white py-12 text-center">
          <p className="text-gray-400">SOPs are loaded in the knowledge base</p>
          <p className="mt-1 text-xs text-gray-400">SOPs auto-match to support tickets when created</p>
        </div>
      )}

      {/* Ticket Detail Panel */}
      <AnimatePresence>
        {selectedTicket && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-black/30"
              onClick={() => setSelectedTicket(null)}
            />
            <motion.div
              role="dialog"
              aria-modal="true"
              aria-label={`Ticket: ${selectedTicket.subject}`}
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 30, stiffness: 300 }}
              className="fixed right-0 top-0 z-50 h-full w-full max-w-lg overflow-y-auto bg-white shadow-2xl"
            >
              <div className="border-b border-gray-100 px-6 py-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-lg font-bold text-gray-900">{selectedTicket.id}</h2>
                    <p className="text-sm text-gray-500">{selectedTicket.subject}</p>
                  </div>
                  <button onClick={() => setSelectedTicket(null)} aria-label="Close panel" className="rounded-full p-2 hover:bg-gray-100">
                    <svg className="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="space-y-4 p-6">
                <div className="rounded-lg bg-gray-50 p-4">
                  <p className="mb-1 text-xs font-medium text-gray-400">From: {selectedTicket.clientName} ({selectedTicket.email})</p>
                  <p className="text-sm text-gray-700">{selectedTicket.message}</p>
                </div>

                {/* Auto-response */}
                {selectedTicket.autoResponse && selectedTicket.status === "open" && (
                  <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4">
                    <p className="mb-2 text-xs font-semibold text-emerald-700">Suggested Auto-Response</p>
                    <p className="whitespace-pre-wrap text-sm text-emerald-800">{selectedTicket.autoResponse}</p>
                    <div className="mt-3 flex gap-2">
                      <button
                        onClick={() => sendResponse(selectedTicket.id, selectedTicket.autoResponse!, true)}
                        className="rounded-lg bg-emerald-600 px-4 py-2 text-xs font-medium text-white hover:bg-emerald-700"
                      >
                        Send Auto-Response
                      </button>
                      <button
                        onClick={() => resolveTicket(selectedTicket.id)}
                        className="rounded-lg border border-gray-200 px-4 py-2 text-xs font-medium text-gray-600 hover:bg-gray-50"
                      >
                        Resolve
                      </button>
                    </div>
                  </div>
                )}

                {/* Responses */}
                {selectedTicket.responses.length > 0 && (
                  <div>
                    <p className="mb-2 text-xs font-medium text-gray-500">Responses</p>
                    {selectedTicket.responses.map((r) => (
                      <div key={r.id} className="mb-2 rounded-lg bg-blue-50 p-3">
                        <p className="text-sm text-blue-800">{r.message}</p>
                        <p className="mt-1 text-[10px] text-blue-400">
                          {r.isAutoGenerated ? "Auto-generated" : "Manual"} &middot; {new Date(r.sentAt).toLocaleString()}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

                {/* Matched FAQs */}
                {selectedTicket.matchedFaqs.length > 0 && (
                  <div>
                    <p className="mb-2 text-xs font-medium text-gray-500">Matched FAQs</p>
                    <p className="text-xs text-gray-400">{selectedTicket.matchedFaqs.length} FAQ(s) matched this ticket</p>
                  </div>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
