/**
 * NorthStar Synergy Business Operations Types
 *
 * Core types for CRM, outreach, clients, finance, support, and digest systems.
 */

// === CRM / PIPELINE ===

export type LeadStage =
  | "prospect"
  | "outreach"
  | "demo"
  | "proposal"
  | "close"
  | "onboarding"
  | "onboarding_complete"
  | "active"
  | "churned";

export type LeadSource =
  | "google_scraper"
  | "referral"
  | "inbound"
  | "manual"
  | "website";

export interface Lead {
  id: string;
  restaurantName: string;
  contactName?: string;
  email?: string;
  phone?: string;
  website?: string;
  address: string;
  city: string;
  state: string;
  stage: LeadStage;
  source: LeadSource;
  score: number;
  previewUrl?: string;
  tags: string[];
  notes: LeadNote[];
  outreachHistory: OutreachEvent[];
  value: number;
  createdAt: string;
  updatedAt: string;
  lastContactedAt?: string;
  nextFollowUpAt?: string;
}

export interface LeadNote {
  id: string;
  content: string;
  createdAt: string;
}

export interface OutreachEvent {
  id: string;
  type: "email" | "call" | "postcard" | "sms" | "meeting" | "manual";
  subject?: string;
  status: "sent" | "delivered" | "opened" | "clicked" | "replied" | "bounced" | "failed";
  sentAt: string;
  openedAt?: string;
  clickedAt?: string;
  repliedAt?: string;
  metadata?: Record<string, string>;
}

// === EMAIL SEQUENCES ===

export interface EmailSequence {
  id: string;
  name: string;
  description: string;
  steps: EmailSequenceStep[];
  isActive: boolean;
  createdAt: string;
}

export interface EmailSequenceStep {
  id: string;
  dayOffset: number;
  subject: string;
  body: string;
  templateId?: string;
}

export interface EmailEnrollment {
  id: string;
  leadId: string;
  sequenceId: string;
  currentStep: number;
  status: "active" | "completed" | "paused" | "unsubscribed";
  enrolledAt: string;
  lastStepSentAt?: string;
  nextStepAt?: string;
}

// === CLIENT PORTFOLIO ===

export interface Client {
  id: string;
  leadId?: string;
  restaurantName: string;
  contactName: string;
  email: string;
  phone: string;
  plan: "starter" | "growth" | "pro";
  status: "active" | "trial" | "past_due" | "cancelled";
  domain?: string;
  deployUrl: string;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  monthlyRevenue: number;
  hostingHealth: "healthy" | "degraded" | "down";
  lastDeployAt?: string;
  sslExpiry?: string;
  notes: string[];
  onboardedAt: string;
  createdAt: string;
  updatedAt: string;
}

// === P&L / FINANCIAL ===

export type ExpenseCategory =
  | "hosting"
  | "email"
  | "sms"
  | "postcards"
  | "voice_ai"
  | "payment_processing"
  | "software"
  | "tax"
  | "marketing"
  | "other";

export interface Expense {
  id: string;
  description: string;
  amount: number;
  category: ExpenseCategory;
  isRecurring: boolean;
  recurringInterval?: "monthly" | "annual";
  date: string;
  createdAt: string;
}

export interface RevenueEntry {
  id: string;
  clientId: string;
  clientName: string;
  amount: number;
  type: "subscription" | "setup_fee" | "addon";
  date: string;
  stripeInvoiceId?: string;
}

export interface PnLSummary {
  period: string;
  totalRevenue: number;
  totalExpenses: number;
  netProfit: number;
  margin: number;
  revenueByClient: Array<{ clientId: string; name: string; amount: number }>;
  expensesByCategory: Array<{ category: ExpenseCategory; amount: number }>;
  mrr: number;
  activeClients: number;
  newClients: number;
  churnedClients: number;
}

// === CUSTOMER SERVICE ===

export interface FaqArticle {
  id: string;
  question: string;
  answer: string;
  category: string;
  tags: string[];
  isPublic: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface Sop {
  id: string;
  title: string;
  category: string;
  steps: string[];
  triggers?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface SupportTicket {
  id: string;
  clientId?: string;
  clientName: string;
  email: string;
  subject: string;
  message: string;
  status: "open" | "in_progress" | "waiting" | "resolved" | "closed";
  priority: "low" | "medium" | "high" | "urgent";
  autoResponse?: string;
  matchedFaqs: string[];
  matchedSops: string[];
  responses: TicketResponse[];
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
}

export interface TicketResponse {
  id: string;
  message: string;
  isAutoGenerated: boolean;
  sentAt: string;
}

// === WEEKLY DIGEST ===

export interface WeeklyDigest {
  id: string;
  weekOf: string;
  generatedAt: string;
  sections: {
    revenue: {
      thisWeek: number;
      lastWeek: number;
      changePercent: number;
      mrr: number;
    };
    pipeline: {
      newLeads: number;
      emailsSent: number;
      responses: number;
      meetings: number;
      closedWon: number;
      closedLost: number;
    };
    clients: {
      total: number;
      newThisWeek: number;
      churnedThisWeek: number;
      healthIssues: Array<{ clientId: string; name: string; issue: string }>;
    };
    support: {
      ticketsOpened: number;
      ticketsResolved: number;
      avgResponseTime: number;
    };
    actionItems: string[];
    highlights: string[];
    concerns: string[];
  };
  sentTo?: string;
  sentAt?: string;
}

// === ACTIVITY LOG ===

export interface ActivityEvent {
  id: string;
  type: "lead" | "outreach" | "client" | "revenue" | "support" | "system";
  action: string;
  description: string;
  entityId?: string;
  entityName?: string;
  metadata?: Record<string, string>;
  createdAt: string;
}
